<?php
// $Id: admin.php,v 1.3 2005/10/19 17:20:33 phppp Exp $
if(defined('NEWBB_ADMIN_DEFINED')) return;
else define('NEWBB_ADMIN_DEFINED', true);
//%%%%%%	File Name  index.php   	%%%%%
define('_AM_NEWBB_FORUMCONF', "Конфігурації форуму");
define('_AM_NEWBB_ADDAFORUM', "Додати форум");
define('_AM_NEWBB_SYNCFORUM', "Синхронізувати форум");
define('_AM_NEWBB_REORDERFORUM', "Перепорядкувати");
define('_AM_NEWBB_FORUM_MANAGER', "Форуми");
define('_AM_NEWBB_PRUNE_TITLE', "Скоротити");
define('_AM_NEWBB_CATADMIN', "Категорії");
define('_AM_NEWBB_GENERALSET', "Модуль налаштуваннь");
define('_AM_NEWBB_MODULEADMIN', "Адмін модуль:");
define('_AM_NEWBB_HELP', "Допомога");
define('_AM_NEWBB_ABOUT', "Інформація");
define('_AM_NEWBB_BOARDSUMMARY', "Статистика форуму");
define('_AM_NEWBB_PENDING_POSTS_FOR_AUTH', "Повідомлення очікуючі авторизації");
define('_AM_NEWBB_POSTID', "Поставити ID");
define('_AM_NEWBB_POSTDATE', "Поставити дату");
define('_AM_NEWBB_POSTER', "Постер");
define('_AM_NEWBB_TOPICS', "Теми");
define('_AM_NEWBB_SHORTSUMMARY', "Резюме форму");
define('_AM_NEWBB_TOTALPOSTS', "Загальна кількість повідомлень");
define('_AM_NEWBB_TOTALTOPICS', "Загальна кількість тем");
define('_AM_NEWBB_TOTALVIEWS', "Загальна кількість переглядів");
define('_AM_NEWBB_BLOCKS', "Блоки");
define('_AM_NEWBB_SUBJECT', "Тема");
define('_AM_NEWBB_APPROVE', "Підтвердити повідомлення");
define('_AM_NEWBB_APPROVETEXT', "Контент цього повідомлення");
define('_AM_NEWBB_POSTAPPROVED', "Повідомлення підтвердженно");
define('_AM_NEWBB_POSTNOTAPPROVED', "Повідомленна НЕ підтвердженно");
define('_AM_NEWBB_POSTSAVED', "Повідомлення збережено");
define('_AM_NEWBB_POSTNOTSAVED', "Повідомленні НЕ збережено");
define('_AM_NEWBB_TOPICAPPROVED', "Тема підтвердженна");
define('_AM_NEWBB_TOPICNOTAPPROVED', "Тема Не підтвердженна");
define('_AM_NEWBB_TOPICID', "ID теми");
define('_AM_NEWBB_ORPHAN_TOPICS_FOR_AUTH', "Авторизація непідтверджених тем");
define('_AM_NEWBB_DEL_ONE', "Видалити тільки це повідомлення");
define('_AM_NEWBB_POSTSDELETED', "Обране повідомлення видалено.");
define('_AM_NEWBB_NOAPPROVEPOST', "Немає повідомлень очікуючих на підтвердження.");
define('_AM_NEWBB_SUBJECTC', "Тема:");
define('_AM_NEWBB_MESSAGEICON', "Іконка повідомлення:");
define('_AM_NEWBB_MESSAGEC', "Повідомлення:");
define('_AM_NEWBB_CANCELPOST', "Відмінити повідомлення");
define('_AM_NEWBB_GOTOMOD', "Перейти до модуля");
define('_AM_NEWBB_PREFERENCES', "Переференції модуля");
define('_AM_NEWBB_POLLMODULE', "Xoops Poll Module");
define('_AM_NEWBB_POLL_OK', "Готовий до використання");
define('_AM_NEWBB_GDLIB1', "GD1 бібліотека:");
define('_AM_NEWBB_GDLIB2', "GD2 бібліотека:");
define('_AM_NEWBB_AUTODETECTED', "Самовизначення: ");
define('_AM_NEWBB_AVAILABLE', "Доступний");
define('_AM_NEWBB_NOTAVAILABLE', '<font color="red">недоступний. </font>');
define('_AM_NEWBB_NOTWRITABLE', '<font color="red">Не записуємий</font>');
define('_AM_NEWBB_IMAGEMAGICK', "ImageMagicK:");
define('_AM_NEWBB_IMAGEMAGICK_NOTSET', "Не встановлювати");
define('_AM_NEWBB_ATTACHPATH', "Шлях для збереження вкладень");
define('_AM_NEWBB_THUMBPATH', "Шлях для прікріплених превью зображень");
//define('_AM_NEWBB_RSSPATH', "Шлях для RSS поданого матеріалу");
define('_AM_NEWBB_REPORT', "Відповідені повідомлення");
define('_AM_NEWBB_REPORT_PENDING', "Очікуючі відповіді");
define('_AM_NEWBB_REPORT_PROCESSED', "В обробці");
define('_AM_NEWBB_CREATETHEDIR', "Створити");
define('_AM_NEWBB_SETMPERM', "Встановити дозвіл");
define('_AM_NEWBB_DIRCREATED', "Діректорія була створена");
define('_AM_NEWBB_DIRNOTCREATED', "Неможливо створити діректорію");
define('_AM_NEWBB_PERMSET', "Дозвіл встановлено");
define('_AM_NEWBB_PERMNOTSET', "Дозвіл не встановлено");
define('_AM_NEWBB_DIGEST', "Повідомлення дайджесту");
define('_AM_NEWBB_DIGEST_PAST', '<font color="red">Повинно бути відправлено %d хвилин тому</font>');
define('_AM_NEWBB_DIGEST_NEXT', "Необхідно відправити через %d хвилин");
define('_AM_NEWBB_DIGEST_ARCHIVE', "Архів дайджесту");
define('_AM_NEWBB_DIGEST_SENT', "Дайджест оброблено");
define('_AM_NEWBB_DIGEST_FAILED', "Дайджест НЕ оброблено");
// admin_forum_manager.php
define('_AM_NEWBB_NAME', "Ім'я");
define('_AM_NEWBB_CREATEFORUM', "Створити форум");
define('_AM_NEWBB_EDIT', "Редагувати");
define('_AM_NEWBB_CLEAR', "Очистити");
define('_AM_NEWBB_DELETE', "Видалити");
define('_AM_NEWBB_ADD', "Додати");
define('_AM_NEWBB_MOVE', "Передвинути");
define('_AM_NEWBB_ORDER', "Впорядкувати");
define('_AM_NEWBB_TWDAFAP', "Примітка: Це буде видалено з форуму та усі повідомлення.<br /><br />УВАГА: Ві впевнені, що хотите видалити цей Форум?");
define('_AM_NEWBB_FORUMREMOVED', "Форум видалено.");
define('_AM_NEWBB_CREATENEWFORUM', "Створити новий форум");
define('_AM_NEWBB_EDITTHISFORUM', "Редагування форуму:");
define('_AM_NEWBB_SET_FORUMORDER', "Встановити позицію форуму:");
define('_AM_NEWBB_ALLOWPOLLS', "Дозволити опитування:");
define('_AM_NEWBB_ATTACHMENT_SIZE', "Макс розмір у Кб:");
define('_AM_NEWBB_ALLOWED_EXTENSIONS', "Дозволені розширення :<span style='font-size: xx-small; font-weight: normal; display: block;'>'*' означає немає обмежень. <br /> розширення обмежені '|'</span>");
define('_AM_NEWBB_ALLOW_ATTACHMENTS', "Дозволити вкладення: ");
define('_AM_NEWBB_ALLOWHTML', "Дозволити HTML:");
define('_AM_NEWBB_YES', "Так");
define('_AM_NEWBB_NO', "Ні");
// irmtfan remove define('_AM_NEWBB_ALLOWSIGNATURES', "Дозволити підписи:");
define('_AM_NEWBB_HOTTOPICTHRESHOLD', "Популярні теми напередодні:");
//define('_AM_NEWBB_POSTPERPAGE', "Повідомлення посторінково:<span style='font-size: xx-small; font-weight: normal; display: block;'>(This is the number of posts<br /> per topic that will be<br /> displayed per page.)</span>");
//define('_AM_NEWBB_TOPICPERFORUM', "Теми на Форумі:<span style='font-size: xx-small; font-weight: normal; display: block;'>(This is the number of topics<br /> per forum that will be<br /> displayed per page.)</span>");
//define('_AM_NEWBB_SHOWNAME', "Замінити ім'я користувача реальним іменем:");
//define('_AM_NEWBB_SHOWICONSPANEL', "Показати панель іконок:");
//define('_AM_NEWBB_SHOWSMILIESPANEL', "Показати панель смайлов:");
define('_AM_NEWBB_MODERATOR_REMOVE', "Видалити поточних модераторів");
define('_AM_NEWBB_MODERATOR_ADD', "Додати модераторів");
// admin_cat_manager.php
define('_AM_NEWBB_SETCATEGORYORDER', "Встановити позицію категорії:");
define('_AM_NEWBB_ACTIVE', "Активна");
define('_AM_NEWBB_INACTIVE', "Неактивна");
define('_AM_NEWBB_STATE', "Статус:");
define('_AM_NEWBB_CATEGORYDESC', "Категорія опису:");
define('_AM_NEWBB_SHOWDESC', "Показати опис?");
define('_AM_NEWBB_IMAGE', "Малюнок:");
//define('_AM_NEWBB_SPONSORIMAGE', "Малюнок спонсора:");
define('_AM_NEWBB_SPONSORLINK', "Посилання на спонсора:");
define('_AM_NEWBB_DELCAT', "Видалити категорію");
define('_AM_NEWBB_WAYSYWTDTTAL', "Примітка: Це НЕ видалиться з підкатегорії форуму, вам необхідно зробити це через Редагування Форуму.<br /><br /> УВАГА: Ві впевненні, що хочете видалити цю категорію?");
//%%%%%%        File Name  admin_forums.php           %%%%%
define('_AM_NEWBB_FORUMNAME', "Назва форуму:");
define('_AM_NEWBB_FORUMDESCRIPTION', "Опис форуму:");
define('_AM_NEWBB_MODERATOR', "Модератор(и):");
define('_AM_NEWBB_REMOVE', "Видалити");
define('_AM_NEWBB_CATEGORY', "Категорія:");
define('_AM_NEWBB_DATABASEERROR', "Помилка бази даних");
define('_AM_NEWBB_CATEGORYUPDATED', "Категорію оновлено.");
define('_AM_NEWBB_EDITCATEGORY', "Редагування категорії:");
define('_AM_NEWBB_CATEGORYTITLE', "Назва категорії:");
define('_AM_NEWBB_CATEGORYCREATED', "Категорію створено.");
define('_AM_NEWBB_CREATENEWCATEGORY', "Створити нову категорію");
define('_AM_NEWBB_FORUMCREATED', "Форум створено.");
define('_AM_NEWBB_ACCESSLEVEL', "Глобальний рівень доступу:");
define('_AM_NEWBB_CATEGORY1', "Категорія");
define('_AM_NEWBB_FORUMUPDATE', "Налаштування форуму оновлено");
define('_AM_NEWBB_FORUM_ERROR', "ПОМИЛКА: помилка в налаштуваннях форуму");
define('_AM_NEWBB_CLICKBELOWSYNC', "Натиснення кнопки нижче синхронізує ваші форуми та сторінки тем за датою з бази даних.  Використовуйте цю опцію , якщо зауважите недоліки у списках тем та форумів. ");
define('_AM_NEWBB_SYNCHING', "Синхронизація списку форумів та тем (Це може зайняти деякий час)");
define('_AM_NEWBB_CATEGORYDELETED', "Категорія видалена");
define('_AM_NEWBB_MOVE2CAT', "Перемістити до категорії:");
define('_AM_NEWBB_MAKE_SUBFORUM_OF', "Створити підфорум:");
define('_AM_NEWBB_MSG_FORUM_MOVED', "Форум переміщено!");
define('_AM_NEWBB_MSG_ERR_FORUM_MOVED', "Помилка в переміщенні форуму.");
define('_AM_NEWBB_SELECT', "< Обрати >");
define('_AM_NEWBB_MOVETHISFORUM', "Перемістити цей Форум");
define('_AM_NEWBB_MERGE', "Об'єднати");
define('_AM_NEWBB_MERGETHISFORUM', "Об'єднати цей Форум");
define('_AM_NEWBB_MERGETO_FORUM', "Об'єднати цей форум з :");
define('_AM_NEWBB_MSG_FORUM_MERGED', "Форум об'єднано!");
define('_AM_NEWBB_MSG_ERR_FORUM_MERGED', "Помилка в об'єднанні форуму.");
//%%%%%%        File Name  admin_forum_reorder.php           %%%%%
define('_AM_NEWBB_REORDERID', "ID");
define('_AM_NEWBB_REORDERTITLE', "Назва");
define('_AM_NEWBB_REORDERWEIGHT', "Позиція");
define('_AM_NEWBB_SETFORUMORDER', "Встановити впорядкування Форуму");
define('_AM_NEWBB_BOARDREORDER', "Форуму було перевпорядковано згідно з вашими вимогами");
// admin_permission.php
define('_AM_NEWBB_PERMISSIONS_TO_THIS_FORUM', "Дозволені теми на цьому Форумі");
define('_AM_NEWBB_CAT_ACCESS', "Доступ категорій");
define('_AM_NEWBB_CAN_ACCESS', "Може мати доступ до категорій");
define('_AM_NEWBB_CAN_VIEW', "Може переглядати контент тем");
define('_AM_NEWBB_CAN_POST', "Може починати нові теми");
define('_AM_NEWBB_CAN_REPLY', "Може відповідати");
define('_AM_NEWBB_CAN_EDIT', "Може редагувати свої повідомлення");
define('_AM_NEWBB_CAN_DELETE', "Може видаляти свої повідомлення");
define('_AM_NEWBB_CAN_ADDPOLL', "Може додавати опитування");
define('_AM_NEWBB_CAN_VOTE', "Може голосувати");
define('_AM_NEWBB_CAN_ATTACH', "Може використовувати прикріплдення");
define('_AM_NEWBB_CAN_NOAPPROVE', "Може напряму публікувати повідомлення");
define('_AM_NEWBB_CAN_TYPE', "Може використовувати вид теми");
define('_AM_NEWBB_CAN_HTML', "Може використовувати та неактивувати/активувати HTML у повідомленнях");//irmtfan revised
define('_AM_NEWBB_CAN_SIGNATURE', "Може використовувати та неактивувати/активувати підпис. За замовчання встановленно у модулі профіль.");//irmtfan revised
define('_AM_NEWBB_ACTION', "Дія");
define('_AM_NEWBB_PERM_TEMPLATE', "Встановити шаблон дозволу за замовчанням");
define('_AM_NEWBB_PERM_TEMPLATE_DESC', "Редагувати наступний шаблон дозволу, так щоб подати заявку на форум або декілька форумів");
define('_AM_NEWBB_PERM_FORUMS', "Обрати форуми");
define('_AM_NEWBB_PERM_TEMPLATE_CREATED', "Шаблон дозволу створено");
define('_AM_NEWBB_PERM_TEMPLATE_ERROR', "Помилка виникає при створенні шаблону дозволу");
define('_AM_NEWBB_PERM_TEMPLATEAPP', "Заповнити дозвіл за замовчанням");
define('_AM_NEWBB_PERM_TEMPLATE_APPLIED', "Дозволи за замованням були застосовані до форумів");
define('_AM_NEWBB_PERM_ACTION', "Інструменти управління дозволом");
define('_AM_NEWBB_PERM_SETBYGROUP', "Встановили дозволи напряму до груп");
// admin_forum_prune.php
define('_AM_NEWBB_PRUNE_RESULTS_TITLE', "Очистити результати");
define('_AM_NEWBB_PRUNE_RESULTS_TOPICS', "Очищені Теми");
define('_AM_NEWBB_PRUNE_RESULTS_POSTS', "Очищені повідомлення");
define('_AM_NEWBB_PRUNE_RESULTS_FORUMS', "Очищені  форуми");
define('_AM_NEWBB_PRUNE_STORE', "Зберігти повідомлення замість того, щоб видалити їх");
define('_AM_NEWBB_PRUNE_ARCHIVE', "Зберігти копію повідомлень до Архіву");
define('_AM_NEWBB_PRUNE_FORUMSELERROR', "Ви забули обрати форум(и) для очищення");
define('_AM_NEWBB_PRUNE_DAYS', "Перемістити теми без відповідей до:");
define('_AM_NEWBB_PRUNE_FORUMS', "Форуми очищені");
define('_AM_NEWBB_PRUNE_STICKY', "Втримувати популярні теми");
define('_AM_NEWBB_PRUNE_DIGEST', "Втримувати дайджест тем");
define('_AM_NEWBB_PRUNE_LOCK', "Втримувати закриті теми");
define('_AM_NEWBB_PRUNE_HOT', "Втримувати теми з кількістю відповідей більше ніж");
define('_AM_NEWBB_PRUNE_SUBMIT', "Ok");
define('_AM_NEWBB_PRUNE_RESET', "Перезапуск");
define('_AM_NEWBB_PRUNE_YES', "Так");
define('_AM_NEWBB_PRUNE_NO', "Ні");
define('_AM_NEWBB_PRUNE_WEEK', "Тиждень");
define('_AM_NEWBB_PRUNE_2WEEKS', "2 Тижні");
define('_AM_NEWBB_PRUNE_MONTH', "Місяць");
define('_AM_NEWBB_PRUNE_2MONTH', "2 Місяці");
define('_AM_NEWBB_PRUNE_4MONTH', "4 Місяці");
define('_AM_NEWBB_PRUNE_YEAR', "Рік");
define('_AM_NEWBB_PRUNE_2YEARS', "2 Роки");
// About.php constants
define('_AM_NEWBB_AUTHOR_INFO', "Авторська інформація");
define('_AM_NEWBB_AUTHOR_NAME', "Автор");
define('_AM_NEWBB_AUTHOR_WEBSITE', "Веб-сайт автора");
define('_AM_NEWBB_AUTHOR_EMAIL', "Пошта автора");
define('_AM_NEWBB_AUTHOR_CREDITS', "Кредити");
define('_AM_NEWBB_MODULE_INFO', "Модуль розвитку інформації");
define('_AM_NEWBB_MODULE_STATUS', "Статус");
define('_AM_NEWBB_MODULE_DEMO', "Демо-Сайт");
define('_AM_NEWBB_MODULE_SUPPORT', "Офіціальний сайт підтримки");
define('_AM_NEWBB_MODULE_BUG', "Доповісти про помилку у цьому модулі");
define('_AM_NEWBB_MODULE_FEATURE', "Запропонувати нову функцію для цього модулю");
define('_AM_NEWBB_MODULE_DISCLAIMER', "Відмова");
define('_AM_NEWBB_AUTHOR_WORD', "Слова автора");
define('_AM_NEWBB_BY', "Ким");
define('_AM_NEWBB_AUTHOR_WORD_EXTRA', "Додаткові слова з модуля автора");
// admin_report.php
define('_AM_NEWBB_REPORTADMIN', "Відправлені повідомлення");
define('_AM_NEWBB_PROCESSEDREPORT', "Переглянути доклади в обробці");
define('_AM_NEWBB_PROCESSREPORT', "Переглянути нові доклади");
define('_AM_NEWBB_REPORTTITLE', "Заголовок докладу");
define('_AM_NEWBB_REPORTEXTRA', "Додатково");
define('_AM_NEWBB_REPORTPOST', "Повідомлення докладу");
define('_AM_NEWBB_REPORTTEXT', "Текст докладу");
define('_AM_NEWBB_REPORTMEMO', "Процес запам'ятовування");
// admin_report.php
define('_AM_NEWBB_DIGESTADMIN', "Дайджест менеджер");
define('_AM_NEWBB_DIGESTCONTENT', "Дайджест контент");
// admin_votedata.php
define('_AM_NEWBB_VOTE_RATINGINFOMATION', "Інформація для голосування");
define('_AM_NEWBB_VOTE_TOTALVOTES', "Усього голосів: ");
define('_AM_NEWBB_VOTE_REGUSERVOTES', "Голоси зареєстрованих користувачів : %s");
define('_AM_NEWBB_VOTE_ANONUSERVOTES', "Голоси анонімних користувачів:%s");
define('_AM_NEWBB_VOTE_USER', "Користувач");
define('_AM_NEWBB_VOTE_IP', "IP адреса");
define('_AM_NEWBB_VOTE_USERAVG', "Середній рейтинг користувача");
define('_AM_NEWBB_VOTE_TOTALRATE', "Підсумковий рейтинг");
define('_AM_NEWBB_VOTE_DATE', "Поданний");
define('_AM_NEWBB_VOTE_RATING', "Рейтинг");
define('_AM_NEWBB_VOTE_NOREGVOTES', "Немає голосів зареєстрованих користувачів");
define('_AM_NEWBB_VOTE_NOUNREGVOTES', "Немає голосів незареєстрованих користувачів");
define('_AM_NEWBB_VOTEDELETED', "Дані голосування видалені.");
define('_AM_NEWBB_VOTE_ID', "ID");
define('_AM_NEWBB_VOTE_FILETITLE', "Головна назва");
define('_AM_NEWBB_VOTE_DISPLAYVOTES', "Інформаційні дані по голосуванню");
define('_AM_NEWBB_VOTE_NOVOTES', "Немає голосів користувачів для відображення");
define('_AM_NEWBB_VOTE_DELETE', "Немає голосів користувачів для видалення");
define('_AM_NEWBB_VOTE_DELETEDSC', "<strong>Видалення</strong> обрана інформація по голосуванню з бази даних.");
// admin_type_manager.php
define('_AM_NEWBB_TYPE_ADD', "Додати типи");
define('_AM_NEWBB_TYPE_TEMPLATE', "Тип шаблону");
define('_AM_NEWBB_TYPE_TEMPLATE_APPLY', "Подати шаблон");
define('_AM_NEWBB_TYPE_FORUM', "По типу на форум");
define('_AM_NEWBB_TYPE_NAME', "Тип імені");
define('_AM_NEWBB_TYPE_COLOR', "Колір");
define('_AM_NEWBB_TYPE_DESCRIPTION', "Опис");
define('_AM_NEWBB_TYPE_ORDER', "Порядок");
define('_AM_NEWBB_TYPE_LIST', "Тип списку");
define('_AM_NEWBB_TODEL_TYPE', "Ви впевнені, що хочете видалити типи: [%s]?");
define('_AM_NEWBB_TYPE_EDITFORUM_DESC', "Дані ще не було збережено. Ви повинні подати заявку,щоб зберегти це. ");
define('_AM_NEWBB_TYPE_ORDER_DESC', "Щоб активувати тип для форуму, необхідно значення більше 0 для 'type_order'; Іншими словами, тип буде дезактивовано для форуму, якщо 'type_order' дорівнює 0.");
// admin_synchronization.php
define('_AM_NEWBB_SYNC_TYPE_FORUM', "Дані форуму");
define('_AM_NEWBB_SYNC_TYPE_TOPIC', "Дані теми");
define('_AM_NEWBB_SYNC_TYPE_POST', "Дані повідомлення");
define('_AM_NEWBB_SYNC_TYPE_USER', "Дані користувача");
define('_AM_NEWBB_SYNC_TYPE_STATS', "Статистична інформація");
define('_AM_NEWBB_SYNC_TYPE_MISC', "Різне");
define('_AM_NEWBB_SYNC_ITEMS', "Items for each loop: ");
define('_AM_NEWBB_ALLOW_SUBJECT_PREFIX', "Дозволити додатки перед Головним?");
define('_AM_NEWBB_ALLOW_SUBJECT_PREFIX_DESC', "Це дозволяє префікси які додані до назви теми.");
define('_AM_NEWBB_GROUPMOD_TITLE', "Додати модераторів на групу");
define('_AM_NEWBB_GROUPMOD_TITLEDESC', "Дозволяє Вам заходити, користувачі певних груп як модераторам");
define('_AM_NEWBB_GROUPMOD_ALLFORUMS', "Усі форуми");
define('_AM_NEWBB_GROUPMOD_ADDMOD', "Модератори були успішно зареєстронані.");
define('_AM_NEWBB_GROUPMOD_ERRMOD', "У вас помилка!");
// added in V 4.3
define('_AM_NEWBB_UPLOAD', "макс Загрузка кожного файлу:");
define('_AM_NEWBB_MEMLIMITTOLARGE', "Увага! Значення \'memory_limit\' до PHP.INI менший ніж \'post_max_size\'");
define('_AM_NEWBB_MEMLIMITOK', "Файли можуть бути скачані максимум з %s.");
// irmtfan add messages
define('_AM_NEWBB_REPORTSAVE', "Обрані доклади були оброблені успішно");
define('_AM_NEWBB_REPORTDELETE', "Обрані доклади були видалені з бази даних успішно");
define('_AM_NEWBB_REPORTNOTSELECT', "Жодного докладу не обрано!");
define('_AM_NEWBB_SYNC_TYPE_READ', "Читати дані");
define('_AM_NEWBB_DATABASEUPDATED', "База даних оновлена успішно!");
define('_AM_NEWBB_CAN_PDF', "Може створювати pdf файли");
define('_AM_NEWBB_CAN_PRINT', "Може роздрукувати сторінку");
?>