<?php
/**
 * $Id: admin.php 11267 2013-03-20 13:16:32Z cesag $
 * Module: Publisher
 * Author: The SmartFactory <www.smartfactory.ca>
 * Licence: GNU
 */
define("_AM_PUBLISHER_ABOUT","Про");
define("_AM_PUBLISHER_ACTION","Дія");
define("_AM_PUBLISHER_ADD_OPT","Додати %s більше підкатегорій");
define("_AM_PUBLISHER_ADD_OPT_SUBMIT","Додати");
define("_AM_PUBLISHER_ALL","Всі");
define("_AM_PUBLISHER_ALL_EXP","<strong>All status</strong>: Всі статті модуля, незалежно від їх статусу.");
define("_AM_PUBLISHER_ALLITEMS","Всі статті в модулі");
define("_AM_PUBLISHER_ALLITEMSMSG","Оберіть статус, щоб побачити всі доступні статті у вибранному статусі.");
define("_AM_PUBLISHER_APPROVE","Затвердити");
define("_AM_PUBLISHER_APPROVING","Твердження");
define("_AM_PUBLISHER_ASC","Висхідна");
define("_AM_PUBLISHER_AVAILABLE","<span style='font-weight: bold; color: green;'>Available</span>");
define("_AM_PUBLISHER_BACK2IDX","Скасовано. Повернення до індексу");
define("_AM_PUBLISHER_BLOCKS","Блоки усправління");
//define("_AM_PUBLISHER_BODY","Тіло");
//define("_AM_PUBLISHER_BODY_DSC","Головне тіло статті <br><strong>Input Options</strong><span style='font-size: xx-small; font-weight: normal; display: block;'><p>1-Usual text & images with formatting</p>2- Pagewrap as follows<p>[pagewrap=filename.html]</p><p>Or</p>[pagewrap=filename_1.html]<br>[pagebreak] <i>this paginates</i><br>[pagewrap=filename_2.html]<br>etc. <p>Or</p><p>[pagewrap=filename_1.html]<br>[pagewrap=filename_2.html]<br><i>this combines pages</i><p> Для того, щоб Pagewrap, необхідно завантажити html сторінку(и) в yoursite.com/uploads/publisher/content, або просто використати обтікання загрузчиком в нижній частині сторінки. </p><p> Зверніть увагу, що трохи нижче області тіла, ви знайдете список доступних сторінок, які можна вставити в тіло, просто натиснувши на потрібну сторінку.</p></span>");
//define("_AM_PUBLISHER_BODY_REQ","Тіло*");
define("_AM_PUBLISHER_BUTTON_CANCEL","Скасувати");
define("_AM_PUBLISHER_BUTTON_DELETE","Видалити");
define("_AM_PUBLISHER_BUTTON_EDIT","Редагувати");
define("_AM_PUBLISHER_BUTTON_SEARCH","Пошук");
define("_AM_PUBLISHER_BUTTON_SUBMIT","Уявити");
define("_AM_PUBLISHER_BUTTON_UPDATE","Оновлення");
define("_AM_PUBLISHER_CANCEL","Скасувати");
define("_AM_PUBLISHER_CAT_ITEMS","Статті");
define("_AM_PUBLISHER_CAT_ITEMS_DSC","Статті не цієї категорії");
define("_AM_PUBLISHER_CATCOLNAME","Назва");
define("_AM_PUBLISHER_CATCREATED","Нова категорія була створена та збережена!");
define("_AM_PUBLISHER_CATEGORIES","Категорії");
define("_AM_PUBLISHER_CATEGORIES_DSC","Це список усіх створених категорія цього модуля.");
define("_AM_PUBLISHER_CATEGORIES_TITLE","Створені категорії");
define("_AM_PUBLISHER_CATEGORY","Категорія");
define("_AM_PUBLISHER_CATEGORY_CREATE","Створити категорію");
define("_AM_PUBLISHER_CATEGORY_CREATE_INFO","Заповніть наступну форму, щоб створити нову категорію. Новостворена категорія буде автоматично відображатись на сторінці користувача.");
//define("_AM_PUBLISHER_CATEGORY_DSC","Категорія статті.");
define("_AM_PUBLISHER_CATEGORY_EDIT_INFO","Ви можете редагувати цю категорію. Зміни вступлять в силу негайно в сторону користувача.");
define("_AM_PUBLISHER_CATEGORY_HEADER","Заголовок категорії");
define("_AM_PUBLISHER_CATEGORY_HEADER_DSC","");
define("_AM_PUBLISHER_CATEGORY_META_DESCRIPTION","Мета опису");
define("_AM_PUBLISHER_CATEGORY_META_DESCRIPTION_DSC","Для того, щоб допомогти пошуковим системам, ви можете налаштувати мета опису, яку б ви хотіли використати для цієї категорії. Якщо ви залишете це поле порожнім, воно буде автоматично заповнене Описом поля цієї категорії.");
define("_AM_PUBLISHER_CATEGORY_META_KEYWORDS","Мета ключові слова");
define("_AM_PUBLISHER_CATEGORY_META_KEYWORDS_DSC","Для того, щоб допомогти пошуковим системам, ви можете налаштувати мета ключові слова, яку б ви хотіли використати для цієї категорії. Якщо ви залишете це поле порожнім, воно буде автоматично заповнене Описом поля цієї категорії.");
define("_AM_PUBLISHER_CATEGORY_SAVE_ERROR","При створенні категорія сталася помилка. Нижче список помилок :");
define("_AM_PUBLISHER_CATEGORY_SHORT_URL","Коротка адреса URL");
define("_AM_PUBLISHER_CATEGORY_SHORT_URL_DSC","При використанні функції SEO цього модуля, ви можете вказати коротку адресу URL для цієї категорії. Це поле не є обов'язковим.");
define("_AM_PUBLISHER_CATID","ID");
define("_AM_PUBLISHER_CLEAR","Очистити");
define("_AM_PUBLISHER_CLONE_ITEM","Дублікат статті");
define("_AM_PUBLISHER_CLONE_NEW","Дублювання статті");
define("_AM_PUBLISHER_COLDESCRIPT","Опис категорії");
define("_AM_PUBLISHER_COLISDELETED","Категорія %s була видалена.");
define("_AM_PUBLISHER_COLMODIFIED","Категорія була успішно модифікована.");
define("_AM_PUBLISHER_COLPOSIT","Позиція категорії");
define("_AM_PUBLISHER_CREATE","Створити");
define("_AM_PUBLISHER_CREATED","Створено");
define("_AM_PUBLISHER_CREATEITEM","Створити статтю");
define("_AM_PUBLISHER_CREATETHEDIR","Створити папку");
define("_AM_PUBLISHER_CREATINGNEW","Створення нової");
//define("_AM_PUBLISHER_DB_CHECKTABLES","Перевірити таблиці");
//define("_AM_PUBLISHER_DB_CURRENTVER","Поточна версія: <span class='currentVer'>%s</span>");
//define("_AM_PUBLISHER_DB_DBVER","Версія бази данних %s");
//define("_AM_PUBLISHER_DB_MSG_ADD_DATA","Додані дані в таблицю %s");
//define("_AM_PUBLISHER_DB_MSG_ADD_DATA_ERR","Помилка при доданні даних в таблицю %s");
//define("_AM_PUBLISHER_DB_MSG_CHGFIELD","Зміна полів %s в таблиці %s");
//define("_AM_PUBLISHER_DB_MSG_CHGFIELD_ERR","Помилка зміни полів %s в таблиці %s");
//define("_AM_PUBLISHER_DB_MSG_CREATE_TABLE","Таблиця %s створена");
//define("_AM_PUBLISHER_DB_MSG_CREATE_TABLE_ERR","Помилка при створенні таблиці %s");
//define("_AM_PUBLISHER_DB_MSG_NEWFIELD","Успішно додане поле %s");
//define("_AM_PUBLISHER_DB_MSG_NEWFIELD_ERR","Помилка при додаванні поля %s");
//define("_AM_PUBLISHER_DB_NEEDUPDATE","Ваша база данних поза дати. Будь ласка, оновіть ваші таблиці бази данних!");
//define("_AM_PUBLISHER_DB_NEEDUPDATE_WARNING","ПОПЕРЕДЖЕННЯ: The SmartFactory настійно рекомендує Вам зробити резервну копію всіх таблиць Publisher перед оновленням.");
//define("_AM_PUBLISHER_DB_NOUPDATE","Ваша база даних оновлена. Оновлення не потрібні.");
//define("_AM_PUBLISHER_DB_UPDATE_DB","Оновлення Бази даних");
//define("_AM_PUBLISHER_DB_UPDATE_ERR","Помилка оновлення версії %s");
//define("_AM_PUBLISHER_DB_UPDATE_NOW","Оновити зараз!");
//define("_AM_PUBLISHER_DB_UPDATE_OK","Успішне оновлення версії %s");
//define("_AM_PUBLISHER_DB_UPDATE_TO","Оновлення версії %s");
define("_AM_PUBLISHER_DELETE","Видалити");
define("_AM_PUBLISHER_DELETE_CAT_CONFIRM","Будь ласка, зверніть увагу, що при видаленні категорії, всі підкатегорії та статті з цієї категорії будуть видалені, а також поряд з будь-якими зауваженніми, які можуть бути розміщені в зв'язку з цими статтями. Ви впевнені, що хочете видалити цю категорію?");
define("_AM_PUBLISHER_DELETE_CAT_ERROR","Сталась помилка при видаленні цієї категорії.");
define("_AM_PUBLISHER_DELETECOL","Видалити категорію");
define("_AM_PUBLISHER_DELETEITEM","Видалити статтю");
define("_AM_PUBLISHER_DELETETHISFILE","Ви впевнені, що хочете видалити цей файл?");
define("_AM_PUBLISHER_DELETETHISITEM","Ви впевнені, що хочете видалити цей пункт?");
define("_AM_PUBLISHER_DESC","Спадний");
define("_AM_PUBLISHER_DESCRIP","Опис категорії");
define("_AM_PUBLISHER_DESCRIPTION","Опис");
define("_AM_PUBLISHER_DIRCREATED","Папка успішно створена ");
define("_AM_PUBLISHER_DIRNOTCREATED","Папка не може бути створена ");
define("_AM_PUBLISHER_EDITCOL","Редагувати категорію");
define("_AM_PUBLISHER_EDITING","Редагування");
define("_AM_PUBLISHER_EDITITEM","Редагувати статтю");
define("_AM_PUBLISHER_FDELETED","Файл видалено");
define("_AM_PUBLISHER_FILE","Файли");
define("_AM_PUBLISHER_FILE_ADD","Додати файл");
define("_AM_PUBLISHER_FILE_ADDING","Додавання нового файлу");
define("_AM_PUBLISHER_FILE_ADDING_DSC","Будь ласка, заповніть наступну форму, щоб додати файл до цієї статті.");
define("_AM_PUBLISHER_FILE_DELETE_ERROR","Сталася помилка при видаленні цього файлу.");
//define("_AM_PUBLISHER_FILE_DESCRIPTION","Опис");
//define("_AM_PUBLISHER_FILE_DESCRIPTION_DSC","Опис файлу, що буде завантажений.");
define("_AM_PUBLISHER_FILE_EDITING","Редагування файлу");
define("_AM_PUBLISHER_FILE_EDITING_DSC","Ви можете відредагувати цей файл. Зміни будуть відображені на сторінці користувача.");
define("_AM_PUBLISHER_FILE_EDITING_ERROR","Сталася помилка при оновленні файлу.");
define("_AM_PUBLISHER_FILE_EDITING_SUCCESS","Файл був успішно змінений.");
define("_AM_PUBLISHER_FILE_INFORMATIONS","Інформація про файл.");
//define("_AM_PUBLISHER_FILE_NAME","Ім'я");
//define("_AM_PUBLISHER_FILE_NAME_DSC","Ім'я, що буде використано для ідентифікування файлу.");
//define("_AM_PUBLISHER_FILE_STATUS","Файл видимий?");
//define("_AM_PUBLISHER_FILE_STATUS_DSC","Якщо ві оберете "ні", файл не буде видимий  зі сторінки користувача.");
//define("_AM_PUBLISHER_FILE_TO_UPLOAD","Файл для завантаження:");
//define("_AM_PUBLISHER_FILE_UPLOAD_ANOTHER","Завантажте знову");
define("_AM_PUBLISHER_FILEISDELETED","Файл було успішно видалено");
define("_AM_PUBLISHER_FILENAME","Ім'я файлу");
define("_AM_PUBLISHER_FILES_LINKED","Файли пов'язані з цією статтею.");
define("_AM_PUBLISHER_FILEUPLOAD_ERROR","Сталася помилка при завантаженні файлу.");
define("_AM_PUBLISHER_FILEUPLOAD_SUCCESS","Файл був успішно завантажений.");
define("_AM_PUBLISHER_GOMOD","Перейти до модулю");
define("_AM_PUBLISHER_HITS","Успіх");
define("_AM_PUBLISHER_ICO_DELETE","Видалити");
define("_AM_PUBLISHER_ICO_EDIT","Редагувати");
define("_AM_PUBLISHER_ICO_OFFLINE","Офлайн");
define("_AM_PUBLISHER_ICO_ONLINE","Онлайн");
define("_AM_PUBLISHER_ID","Id");
define("_AM_PUBLISHER_IMAGE","Зображення категорії");
define("_AM_PUBLISHER_IMAGE_DSC","Зображення представлене категорією");
define("_AM_PUBLISHER_IMAGE_ITEM","Зображення статті");
//define("_AM_PUBLISHER_IMAGE_ITEM_DSC","Зображення представленне статею");
define("_AM_PUBLISHER_IMAGE_UPLOAD","Зображення завантажено");
define("_AM_PUBLISHER_IMAGE_UPLOAD_DSC","Оберіть зображення на вашому комп'ютері. Це зображення буде завантажено на сайт та обрано, як зображення категорії.");
//define("_AM_PUBLISHER_IMAGE_UPLOAD_ITEM_DSC","Оберіть зображення на вашому комп'ютері. Це зображення буде завантажено на сайт <br /> та обрано, як зображення статті.");
define("_AM_PUBLISHER_IMPORT","Імпорт");
define("_AM_PUBLISHER_IMPORTED_COMMENT","Коментар '%s' імпортован.");
define("_AM_PUBLISHER_IMPORTED_COMMENT_ERROR","Помилка при імпортуванні коментаря '%s' ");
define("_AM_PUBLISHER_IMPORT_COMMENTS","Імпорт коментарів модуля");
define("_AM_PUBLISHER_IMPORTED_ARTICLE_FILE","Пов'язаний файл %s було імпортовано");
define("_AM_PUBLISHER_IMPORT_ARTICLE_ERROR","Помилка при імпортування статті <em>%s</em>");
define("_AM_PUBLISHER_IMPORT_ARTICLE_WRAP","Сторінка загорнутого файлу %s була скопійована в папку модуля.");
define("_AM_PUBLISHER_IMPORT_BACK","Повернутися до сторінки імпорту");
define("_AM_PUBLISHER_IMPORT_CATEGORIES","Категорії були імпортовані");
define("_AM_PUBLISHER_IMPORT_CATEGORIES_DSC","Це категорії, що будуть імпортованні в Publisher");
define("_AM_PUBLISHER_IMPORT_CATEGORY_ERROR","Помилка при імпортування категорії <em>%s</em>.");
define("_AM_PUBLISHER_IMPORT_CATEGORY_SUCCESS","Категорія <em>%s</em> імпортована успішно.");
define("_AM_PUBLISHER_IMPORT_ERROR","Сталася помилка при імпортування статті.");
define("_AM_PUBLISHER_IMPORT_FILE_NOT_FOUND","Імпортований файл не знайдено в <strong>%s</strong>");
define("_AM_PUBLISHER_IMPORT_FROM","Імпортування з %s");
define("_AM_PUBLISHER_IMPORT_GOTOMODULE","До індексної сторінки Publisher");
define("_AM_PUBLISHER_IMPORT_INFO","Ви можете імпортувати статті безпосередньо в Publisher. Просто оберіть з якого модуля ві би хотіли імпортувати статті та натисніть на кнопку 'Імпорт'.<br><strong>Виконуйте цю операцію тільки одни раз, в іншому випадку, вироби будуть дублюватися.");
define("_AM_PUBLISHER_IMPORT_MODULE_FOUND","%s модуль був знайдений. Це %s статті та %s категорії, що можуть бути імпортовані.");
define("_AM_PUBLISHER_IMPORT_MODULE_FOUND_NO_ITEMS","%s модуль знайдений, але немає статей для імпорту.");
define("_AM_PUBLISHER_IMPORT_NOCATSELECTED","Жодна категорія не була обрана для імпорту.");
define("_AM_PUBLISHER_IMPORT_NO_MODULE","Ніякий підтримуючий модуль не встановлен на цьому сайті, стаття не може бути імпортована.");
define("_AM_PUBLISHER_IMPORT_PARENT_CATEGORY","Батьківська категорія");
define("_AM_PUBLISHER_IMPORT_PARENT_CATEGORY_DSC","Імпорт обраних категорій в батьківську.");
define("_AM_PUBLISHER_IMPORT_RESULT","Це результат імпорту.");
define("_AM_PUBLISHER_IMPORT_SETTINGS","Налаштування імпорту");
define("_AM_PUBLISHER_IMPORT_SUCCESS","Статті успішно імпортовані в модуль.");
define("_AM_PUBLISHER_IMPORT_TITLE","Імпорт статей");
define("_AM_PUBLISHER_IMPORTED_ARTICLE","Імпортована стаття: <em>%s</em>");
define("_AM_PUBLISHER_IMPORTED_ARTICLES","Статті імпортовані: <em>%s</em>");
define("_AM_PUBLISHER_IMPORTED_CATEGORIES","Категорії імпортовані: <em>%s</em>");
define("_AM_PUBLISHER_IMPORT_SELECTION","Імпорт вибір");
define("_AM_PUBLISHER_IMPORT_SELECT_FILE","Статті");
define("_AM_PUBLISHER_IMPORT_SELECT_FILE_DSC","Оберіть модуль з якого імпортувати статті.");
define("_AM_PUBLISHER_INDEX","Індекс");
define("_AM_PUBLISHER_INVENTORY","Резюме модуль");
define("_AM_PUBLISHER_ITEM","Стаття");
define("_AM_PUBLISHER_ITEM_CREATING","Створення нової статті");
define("_AM_PUBLISHER_ITEM_CREATING_DSC","Будь ласка, заповніть наступну форму, для того, щоб створити нову статтю.");
define("_AM_PUBLISHER_ITEM_DELETE_ERROR","Сталася помилка при видаленні цієї статті.");
define("_AM_PUBLISHER_ITEM_DUPLICATING","Дублювання статті");
define("_AM_PUBLISHER_ITEM_DUPLICATING_DSC","Редагувати форму, для того, щоб створити нову статтю засновану на оригінальній.");
define("_AM_PUBLISHER_ITEM_EDIT","Редагувати цю статтю");
define("_AM_PUBLISHER_ITEM_RECEIVED_NEED_APPROVAL","Ваша статя була відправлена і буде опублікована після схвалення модератором. <br /> Дякуємо за внесок!");
define("_AM_PUBLISHER_ITEM_REJECTED","Ця стаття була відхилена.");
define("_AM_PUBLISHER_ITEMCAT","Категорія");
define("_AM_PUBLISHER_ITEMCATEGORYNAME","Категорія");
define("_AM_PUBLISHER_ITEMCOLNAME","Назва");
define("_AM_PUBLISHER_ITEMDESC","Опис");
define("_AM_PUBLISHER_ITEMID","ID");
define("_AM_PUBLISHER_ITEMISDELETED","Стаття була видалена.");
define("_AM_PUBLISHER_ITEMNOTCREATED","Вибачте. Неможливо створити цю статтю!");
define("_AM_PUBLISHER_ITEMNOTUPDATED","Вибачте. Неможливо оновити цю статтю!");
define("_AM_PUBLISHER_ITEMS","Статті");
define("_AM_PUBLISHER_MESSAGE_ADD_MIME_ERROR","Помилка: тип мім не був доданий.");
define("_AM_PUBLISHER_MESSAGE_DELETE_MIME_ERROR","Помилка: тип мім не був видалений.");
define("_AM_PUBLISHER_MESSAGE_EDIT_MIME_ERROR","Помилка: тип мім не був оновлений.");
define("_AM_PUBLISHER_MESSAGE_NO_ID","Помилка: ID не було зазначено.");
define("_AM_PUBLISHER_MIME_ADD_TITLE","Додати тип мім.");
define("_AM_PUBLISHER_MIME_ADMIN","Адміністратор");
define("_AM_PUBLISHER_MIME_ADMINF","Дозволити адміністратору тип мім");
define("_AM_PUBLISHER_MIME_CREATE","Створити");
define("_AM_PUBLISHER_MIME_CREATEF","Створити тип мім");
define("_AM_PUBLISHER_MIME_EDIT_TITLE","Редагувати тип мім");
define("_AM_PUBLISHER_MIME_EXT","EXT");
define("_AM_PUBLISHER_MIME_EXTF","Розширення файлу");
define("_AM_PUBLISHER_MIME_FINDIT","Отримати розширення!");
define("_AM_PUBLISHER_MIME_FINDMIMETYPE","Знайти новий тип мім?");
define("_AM_PUBLISHER_MIME_ID","ID");
define("_AM_PUBLISHER_MIME_INFOTEXT","<ul><li>Новий тип мым може бути створений, редагований або видалений просто з цыэъ форми.</li> <li> Шукайте новы типи пантомыми через зовнышный веб-сайт.</li> <li>Перегляд типу пантоміми відбражається для адміністратора та користувача, що завантажив.</li> <li>Змінити статус типу пантоміми.</li></ul>");
define("_AM_PUBLISHER_MIME_MANAGE_TITLE","Управління типами пантоміми");
define("_AM_PUBLISHER_MIME_MODIFY","Змінити");
define("_AM_PUBLISHER_MIME_MODIFYF","Змінити тип пантоміми");
define("_AM_PUBLISHER_MIME_NAME","Тип додатка");
define("_AM_PUBLISHER_MIME_NAMEF","Тим додатка/ім'я<div style='padding-top: 8px;'><span style='font-weight: normal;'>Введіть додаток, пов'язаний з цим розширенням.</span></div>");
define("_AM_PUBLISHER_MIME_SEARCH","Типи мім пошуку");
define("_AM_PUBLISHER_MIME_TYPEF","Типи мім <div style='padding-top: 8px;'><span style='font-weight: normal;'> Введіть кожен тип пантоміми, пов'язаний з розшеренням файлу. Кожен тип повинен біти розділенй пропуском. </span></div>");
define("_AM_PUBLISHER_MIME_USER","Користувач");
define("_AM_PUBLISHER_MIME_USERF","Дозволиний тип мім користувачеві");
define("_AM_PUBLISHER_MIMETYPES","Мім типи");
define("_AM_PUBLISHER_MINDEX_ACTION","Дія");
define("_AM_PUBLISHER_MODIFY","Модифікувати");
define("_AM_PUBLISHER_NEED_CATEGORY_ITEM","Щоб створити статтю, спочатку ві повинні створити категорію.");
define("_AM_PUBLISHER_NO","Ні");
define("_AM_PUBLISHER_NOCAT","Жодної категорії для відображення");
define("_AM_PUBLISHER_NOCOLTOEDIT","Немає категорій для редагування!");
define("_AM_PUBLISHER_NOFILE","Ця стаття не має жодного прикріпленого файлу.");
define("_AM_PUBLISHER_NOFILESELECTED","Немає обраних файлів.");
define("_AM_PUBLISHER_NOITEMS","Жодної опублікованої статті.");
define("_AM_PUBLISHER_NOITEMS_OFFLINE","Жодної офлайн статті.");
define("_AM_PUBLISHER_NOITEMS_REJECTED","Жодної відхиленої статті.");
define("_AM_PUBLISHER_NOITEMS_SUBMITTED","Жодної представленої статті.");
define("_AM_PUBLISHER_NOITEMSELECTED","Жодна стаття не обрана!");
define("_AM_PUBLISHER_NOITEMSSEL","Вибачте. Жодної статті в обраному стані.");
define("_AM_PUBLISHER_NOPERMSSET","Дозвіл не може бути встановлений: Жодної створеної категорії! Будь ласка, в першу чергу створіть категорію.");
define("_AM_PUBLISHER_NOSUBCAT","Жодної підкатегорії ще не створено");
define("_AM_PUBLISHER_NOTAVAILABLE","<span style='font-weight: bold; color: red;'>Недоступно</span>");
define("_AM_PUBLISHER_NOTWRITABLE","<span style='font-weight: bold; color: yellow;'>Не доступний для запису</span>");
define("_AM_PUBLISHER_OFFLINE_CREATED_SUCCESS","Стаття була успішно створена та викладена на сайті.");
define("_AM_PUBLISHER_OFFLINE_EXP","<strong>Офлайн статті</strong>: Опубліковані статті, які були поставлені в автономному режимі, тимчасово чи ні. Оффлайн статті не відображаються в призначеній для користувача сторонці.");
define("_AM_PUBLISHER_OFFLINE_MOD_SUCCESS","Стаття була успішно викладена на сайті.");
define("_AM_PUBLISHER_OFFLINEEDITING","Редагування статті оффлайн.");
define("_AM_PUBLISHER_OFFLINEEDITING_INFO","Ви можете редагувати цю статтю онлайн Зміни будуть збережені для цієї статті. Однак, якщо ви хочете щоб ця стаття відображалась на сторінці користувача, вам потрібно буде встановити статус <strong>Опубліковано</strong>.");
define("_AM_PUBLISHER_PAGEWRAP","Обгортка сторінки");
define("_AM_PUBLISHER_PAGEWRAPDSC","Обгортка-сторінки це можливість зв'язати статтю з файлом контенту. Роблячи це, зміст статті безпосередньо береться з цього файлу і вам не потрібно додавати зміст вручну. Це корисно, коли ви вже відформатували HTML або PHP файли.");
define("_AM_PUBLISHER_PARENT_CATEGORY_EXP","Батьківська категорія<span style='font-size: xx-small; font-weight: normal; display: block;'> Оберіть 'батьки', щоб зробити це підкатегорією.</span>");
define("_AM_PUBLISHER_PERMERROR","Помилка: неможливо отримати доступ до каталогу файлів. Будь ласка, CHMOD завантаження/видавець/каталог вмісту зі значенням 755 (або 777 в залежності від середовища).");
define("_AM_PUBLISHER_PERMISSIONS","Дозволи");
define("_AM_PUBLISHER_PERMISSIONS_APPLY_ON_ITEMS","Застосувати права на читання статей<span style='font-size: xx-small; font-weight: normal; display: block;'> Застосувати вище права на читання всіх <br /> статей в цій категорії, перекриваючи їх<br />поточний дозвіл.<br /><strong>Будь ласка, зверніть увагу, що це одно разова акція, а не властивість.</strong></span>");
define("_AM_PUBLISHER_PERMISSIONS_CAT_READ","Дозволи на читання<span style='font-size: xx-small; font-weight: normal; display: block;'>Групи, які мають дозволи, щоб побачити<br />цю категорію, а також будь-які предмети всередині цієї категорії.</span>");
define("_AM_PUBLISHER_PERMISSIONS_CAT_SUBMIT","Дозволи до уявних статей.");
define("_AM_PUBLISHER_PERMISSIONS_CAT_SUBMIT_DSC","Групи, які будуть мати можливість представити статті в даній категорії. Перевага '[ДОЗВОЛИ] уявних користувачів' повино бути включено.");
define("_AM_PUBLISHER_PERMISSIONSVIEWMAN","Дозволи на перегляд категорій.");
define("_AM_PUBLISHER_PUBLISH","Опублікувати");
define("_AM_PUBLISHER_PUBLISHED_DSC","Це список усіх опублікованих статей, видимих на сторінці користувача.");
define("_AM_PUBLISHER_PUBLISHED_EXP","<strong>Опубліковані статті</strong>:  статті, що були затверджені та відображені на сторінці користувача.");
define("_AM_PUBLISHER_PUBLISHED_MOD_SUCCESS","Стаття була успішно модифікована.");
define("_AM_PUBLISHER_PUBLISHEDEDITING","Редагування опублікованої статті");
define("_AM_PUBLISHER_PUBLISHEDEDITING_INFO","Ви можете відредагувати цю статтю. Зміни вступлять в силу негайно в сторону користувача.");
define("_AM_PUBLISHER_PUBLISHEDITEMS","Опубліковані статті");
define("_AM_PUBLISHER_REJECTED_EDIT","Редагувати цю відхилену статтю");
define("_AM_PUBLISHER_REJECTED_ITEM","Відхилена стаття");
define("_AM_PUBLISHER_REJECTED_ITEM_EXP","<strong>Відкинуті статті</strong>: статті, які були представлені користувачем, але відхилені модератором. Відхилені статті не відображаються в призначеній для користувача сторінці.");
define("_AM_PUBLISHER_RUSUREDELF","Ви впевнені, що хочете видалити цей файл?");
define("_AM_PUBLISHER_SCATEGORYNAME","Створені підкатегорії<br><br><span style='font-size: xx-small; font-weight: normal; display: block;'>Заповніть текстове поле з назвами підкатегорій для створення.<br>Залиште порожнім, щоб не створювати підкатегорію. Для створення більш, введіть наскільки треба, потім натисніть 'Додати'</span>");
define("_AM_PUBLISHER_SEARCH","Пошук");
define("_AM_PUBLISHER_SEARCH_PW","Дозволені тільки HTML, HTM або XHTML розширення");
define("_AM_PUBLISHER_SELECT_SORT","Порядок сортування");
define("_AM_PUBLISHER_SELECT_STATUS","Статус");
define("_AM_PUBLISHER_SHOWING","Показ");
define("_AM_PUBLISHER_STATUS0","Немає статусу");
define("_AM_PUBLISHER_SUBCAT_CAT","Підкатегорії");
define("_AM_PUBLISHER_SUBCAT_CAT_DSC","Це список підкатегорій цієї категорії");
define("_AM_PUBLISHER_SUBCATEGORY_SAVE_ERROR","Сталася помилка при збереженні категорії. Список помилок:");
define("_AM_PUBLISHER_SUBDESCRIPT","Опис");
define("_AM_PUBLISHER_SUBMISSION_MODERATE","Пом'якшити цю статтю");
define("_AM_PUBLISHER_SUBMISSIONSMNGMT","Представлені статті");
define("_AM_PUBLISHER_SUBMIT","Представити");
define("_AM_PUBLISHER_SUBMITTED_APPROVE_SUCCESS","Представлена стаття успішно опублікована на сторінці користувача.");
define("_AM_PUBLISHER_SUBMITTED_EXP","<strong>Представлені статті</strong>: статті, що були представлені користувачами. Один раз затверджені, вони будуть відображатись на сторінці користувача.");
define("_AM_PUBLISHER_SUBMITTED_INFO","Ця стаття була представлена учасником. Ви можете зробити деякі зміни, якщо хочете. На затвердження, ця стаття буде відображатися в призначеній для користувача сторінці на цьому сайті.");
define("_AM_PUBLISHER_SUBMITTED_TITLE","Затвердження представленої статті");
define("_AM_PUBLISHER_SUMMARY","Введення");
//define("_AM_PUBLISHER_SUMMARY_DSC","Введення статті");
define("_AM_PUBLISHER_TEXT_ASCENDING","Висхідна");
define("_AM_PUBLISHER_TEXT_DESCENDING","Спадна");
define("_AM_PUBLISHER_TEXT_NO_RECORDS","Записів не знайдено");
define("_AM_PUBLISHER_TEXT_NUMBER_PER_PAGE","Кількість на сторінку:");
define("_AM_PUBLISHER_TEXT_ORDER_BY","Сортувати за:");
define("_AM_PUBLISHER_TEXT_SEARCH_BY","Пошук по:");
define("_AM_PUBLISHER_TEXT_SEARCH_MIME","Пошук типа мім:");
define("_AM_PUBLISHER_TEXT_SEARCH_TEXT","Пошук тексту:");
define("_AM_PUBLISHER_TEXT_SORT_BY","Сортувати за:");
define("_AM_PUBLISHER_TITLE","Назва");
define("_AM_PUBLISHER_TOTAL_OFFLINE","Статті офлайн: ");
define("_AM_PUBLISHER_TOTALCAT","Категорії:");
define("_AM_PUBLISHER_TOTALPUBLISHED","Опубліковані статті: ");
define("_AM_PUBLISHER_TOTALSUBMITTED","Представлені статті: ");
define("_AM_PUBLISHER_UPDATE_MODULE","Оновити модуль");
define("_AM_PUBLISHER_UPLOAD","Завантажити");
define("_AM_PUBLISHER_UPLOAD_FILE","Завантажити файл");
define("_AM_PUBLISHER_UPLOAD_FILE_NEW","Завантажити новий файл");
define("_AM_PUBLISHER_UPLOADED_DATE","Завантажено");
define("_AM_PUBLISHER_VIEW_CATS","Оберіть категорії, що кажна група може переглянути");
define("_AM_PUBLISHER_YES","Так");
//define("_AM_PUBLISHER_TOOLS","Інструменти");
//define("_AM_PUBLISHER_CONFIGURE_READ_PERMISSIONS","Встановлення роздільної здатності на читання");
//define("_AM_PUBLISHER_CONFIGURE_READ_PERMISSIONS_EXP","Цей інструмент дозволяю Вам швидко встановлювати дозвіл на читання для ВСІХ категорій та ВСІХ статей одразу. УСІ дозволи спочатку видаляться, а потім будуть щаміщені опціями, що ви оберете.<br /><br /><strong>Будь ласка, користуйтесь інструментом з остережністью!</strong>");
//define("_AM_PUBLISHER_FULLACCESS","Категорії та статті дозволені до читання");
//define("_AM_PUBLISHER_PERMISSIONS_UPDATED","Дозволи оновлені.");
define("_AM_PUBLISHER_ITEM_TAG","Теги");
//added in publisher
define("_AM_PUBLISHER_PERMISSIONS_FORM","Поля, доступні в статтях представленних форм");
define("_AM_PUBLISHER_PERMISSIONS_FORM_DSC","Ви можете обрати, які поля необов'язково будуть присутні в представленних статтях форм. Ви можете встановити значення за замовчуванням для цього поля в налаштуваннях.");
define("_AM_PUBLISHER_NOTIFY","Повідомляти про публікацію?");
define("_AM_PUBLISHER_PERMISSIONS_EDITORS","Редактори, доступні в статтях представлених форм");
define("_AM_PUBLISHER_PERMISSIONS_EDITORS_DSC","Ви можете обрати, які редактори доступні в статтях представлених форм.");
define("_AM_PUBLISHER_PERMISSIONS_GLOBAL","Глобальні параметри дозволів");
define("_AM_PUBLISHER_PERMISSIONS_GLOBAL_DSC","Оберіть, які групи можуть виконувати які дії.");
define("_AM_PUBLISHER_RATE","Ставка");
define("_AM_PUBLISHER_CLONE","Клон");
define("_AM_PUBLISHER_CLONE_DSC","Клонування модулю ніколу не біло таким простим! Просто введіть ім'я, яке потрібне для цього і натисніть кнопку надіслати!");
define("_AM_PUBLISHER_CLONE_TITLE","Клон %s");
define("_AM_PUBLISHER_CLONE_NAME","Оберіть ім'я для нового модуля");
define("_AM_PUBLISHER_CLONE_NAME_DSC","Не використовуйте спеціальні символи! <br />Не обирайте існучий модуль або ім'я бази даних!");
define("_AM_PUBLISHER_CLONE_INVALIDNAME","Помилка: Невірне ім'я модуля, спробуйте, будь ласка, ще раз!");
define("_AM_PUBLISHER_CLONE_EXISTS","Помилка: Модульне ім'я вже існує, будь ласка, спробуйте інше!");
define("_AM_PUBLISHER_CLONE_CONGRAT","Вітаємо! %s був успішно створений!<br />Ви можете внести зміни в мовні файли.");
define("_AM_PUBLISHER_CLONE_IMAGEFAIL","Увага, ми не змогли створити новий модуль логотипу. Будь ласка, розгляньте питання про зміну вартості активів/зображень/модуль_лого.png вручну!");
define("_AM_PUBLISHER_CLONE_FAIL","На жаль, мі зазнали невдачі у створенні нового клону. Можливо, вам необхідно тимчасово встановити дозвіл на запис(CHMOD 777) в папку 'модулів' и спробувати ще раз.");
define("_AM_PUBLISHER_COMMENTS","Коментарі");
define("_AM_PUBLISHER_CATEGORY_MODERATOR","Модератор");
define("_AM_PUBLISHER_CATEGORY_MODERATOR_DSC","Модератор може отримати доступ і представити в цій категорії, навіть якщо в нього немає дозволу груп.<br />Щоб пом'якшити вкладену категорію, в якій користувач повинен мати дозвіл представляти в батьківській категорії.<br />Встановіть 'анонім', якщо вам не потрібен модератор.");
//03/05/2012
define("_AM_PUBLISHER_PERMISSIONS_CAT_MODERATOR","Дозвіл на модерацію");
define("_AM_PUBLISHER_PERMISSIONS_CAT_MODERATOR_DSC","Групи, яким дозволять модерувати статті в цій категорії. Користувачі цієї групи зможуть редагувати/видалять/клонувати статті. Не забувайте також встановлювати дозвіл на ці групи!");
//1.01 Beta 1
define("_AM_PUBLISHER_ITEMCATEGORY_ID","ID");
define("_AM_PUBLISHER_ITEM_VIEWS","Перегляди");
