<?php
/**
 * $Id: main.php 11267 2013-03-20 13:16:32Z cesag $
 * Module: Publisher
 * Author: The SmartFactory <www.smartfactory.ca>
 * Licence: GNU
 */
define("_MD_PUBLISHER_ADD_FILE_INTRO","Будь ласка, заповніть цю форму, щоб прикріпити файл до цієї статті: '%s'.");
define("_MD_PUBLISHER_ADD_FILE_TITLE","Додати файл до статті");
define("_MD_PUBLISHER_ADMIN_PAGE",":: Адміністративний розділ ::");
define("_MD_PUBLISHER_MODIFY","Змінити");
define("_MD_PUBLISHER_CANCEL","Скасувати");
define("_MD_PUBLISHER_CATEGORY_EDIT","Редагувати категорію");
define("_MD_PUBLISHER_CATEGORY_SUMMARY","Стислий виклад %s");
define("_MD_PUBLISHER_CATEGORY_SUMMARY_INFO","Підкатегорії з %s.");
define("_MD_PUBLISHER_CLEAR","Очистити");
define("_MD_PUBLISHER_COMMENTS","Коментар(і)");
//define("_MD_PUBLISHER_CREATE","Створити статтю");
define("_MD_PUBLISHER_DATE","Дата");
define("_MD_PUBLISHER_DATESUB","Опублікувано на");
define("_MD_PUBLISHER_DESCRIPTION","Опис");
define("_MD_PUBLISHER_DOWNLOAD_FILE","Завантажити цей файл");
define("_MD_PUBLISHER_EDIT_ARTICLE","Редагувати статтю");
define("_MD_PUBLISHER_EMPTY","Ця категорія в даний час не має жодної статті або підкатегорії.");
define("_MD_PUBLISHER_GOODDAY","Вітаємо <strong>%s</strong>!  ");
define("_MD_PUBLISHER_HITS","Хіти");
define("_MD_PUBLISHER_HITSDETAIL","Ця стаття була прочитана");
define("_MD_PUBLISHER_HOME","Додому");
define("_MD_PUBLISHER_INDEX_CATEGORIES_SUMMARY","Резюме категорій");
define("_MD_PUBLISHER_INDEX_CATEGORIES_SUMMARY_INFO","Це список кращих категорій та іх підкатегорій. Оберіть категорію, щоб побачити статті.");
define("_MD_PUBLISHER_INDEX_ITEMS","Останні опублікованні статті");
define("_MD_PUBLISHER_INDEX_ITEMS_INFO","Це список останніх опублікованих статей.");
define("_MD_PUBLISHER_ITEM","стаття");
define("_MD_PUBLISHER_ITEM_RECEIVED_AND_PUBLISHED","Ваша стаття була надіслана та автоматично опублікована. Дякуємо за ваш внесок!");
define("_MD_PUBLISHER_ITEM_RECEIVED_NEED_APPROVAL","Ваша стаття була відправлена та буде опублікована після схвалення модератором.<br />Дякуємо за ваш внесок!");
define("_MD_PUBLISHER_ITEMMODIFIED","Стаття була успішно змінена!");
define("_MD_PUBLISHER_ITEMS","Статті");
define("_MD_PUBLISHER_ITEMS_INFO","Це статті цієї категорії.");
define("_MD_PUBLISHER_ITEMS_LINKS","Навігація за статтями");
define("_MD_PUBLISHER_ITEMS_TITLE","Статті з %s");
define("_MD_PUBLISHER_LAST_SMARTITEM","Остання опублікована стаття");
define("_MD_PUBLISHER_NAME","Ім'я");
define("_MD_PUBLISHER_NEED_CATEGORY_ITEM","Щоб створити статтю, ви повинні мати відоповідний дозвіл, принаймі однієї категорії.");
define("_MD_PUBLISHER_NEXT_ITEM","Наступна стаття");
define("_MD_PUBLISHER_NO","Ні");
define("_MD_PUBLISHER_NO_CAT_EXISTS","На жаль, &#8217 немає //визначеної категорії ще. <br />Будь ласка, зв'яжіться з адміністратором і повідомте його про це.");
define("_MD_PUBLISHER_NO_CAT_PERMISSIONS","Вибачте, ви не маєте дозвіл на доступ до цієї області.");
define("_MD_PUBLISHER_NO_TOP_PERMISSIONS","Вибачте, немає статей для відображення.");
define("_MD_PUBLISHER_NOCATEGORYSELECTED","Ви не обрали дійсну категорію!");
define("_MD_PUBLISHER_NOITEMSELECTED","Ви не обрали дійсну статтю!");
define("_MD_PUBLISHER_ON","на");
define("_MD_PUBLISHER_OTHER_ITEMS","Інші статті цієї категорії");
define("_MD_PUBLISHER_PAGE","Сторінка");
//define("_MD_PUBLISHER_PREVIEW","Попередній перегляд");
define("_MD_PUBLISHER_PREVIOUS_ITEM","Попередня стаття");
define("_MD_PUBLISHER_PRINTERFRIENDLY","Надрукувати цю статтю в зручному форматі принтера");
define("_MD_PUBLISHER_READS","читає");
define("_MD_PUBLISHER_RSSFEED","RSS Подача");
define("_MD_PUBLISHER_SENDSTORY","Надіслати цю статтю другу");
define("_MD_PUBLISHER_SUB_CLONE","Дублювати статтю");
define("_MD_PUBLISHER_SUB_SMNAME","Представити статтю");
define("_MD_PUBLISHER_SUB_SNEWNAME","Представити статтю");
define("_MD_PUBLISHER_SUBMIT","Представити статтю");
define("_MD_PUBLISHER_SUBMIT_ERROR","Сталася помилка. Ваша стаття не була представлена.");
define("_MD_PUBLISHER_TOTAL_SMARTITEMS","Загальні статті");
define("_MD_PUBLISHER_UPLOAD","Завантажити");
//define("_MD_PUBLISHER_UPLOAD_FILE","Завантажити файл");
define("_MD_PUBLISHER_VIEW_MORE","Читати повну статтю");
define("_MD_PUBLISHER_WHO_WHEN","Опублікована %s на %s");
define("_MD_PUBLISHER_PRINT_CLOSE","Закрити це вікно");
//added in publisher
define("_MD_PUBLISHER_VOTE_BAD","Погана голос, спробуйте, будь ласка, пізніше!");
define("_MD_PUBLISHER_VOTE_ALREADY","Вибачте, ви вже голосували за цей пункт!");
define("_MD_PUBLISHER_VOTE_THANKS","Дякуємо за ваш голос!");
define("_MD_PUBLISHER_VOTE_lVOTE","голос");
define("_MD_PUBLISHER_VOTE_lVOTES","голоси");
define("_MD_PUBLISHER_VOTE_RATING","Рейтинг");
define("_MD_PUBLISHER_VOTE_DISABLE","Голоси відключені!");
define("_MD_PUBLISHER_VOTE_OUTOF","з");
define("_MD_PUBLISHER_ITEMS_SAME_AUTHOR","Деталі щодо автора");
define("_MD_PUBLISHER_TOTAL_ITEMS","Загальні деталі: ");
define("_MD_PUBLISHER_TOTAL_HITS","Загальні хіти: ");
define("_MD_PUBLISHER_NO_AUTHOR_ITEMS","Немає жодних деталей цього автору");
define("_MD_PUBLISHER_ARCHIVES","Архіви статті");
define("_MD_PUBLISHER_ACTIONS","Дії");
define("_MD_PUBLISHER_PREVIOUSIMG","Попереднє зображення");
define("_MD_PUBLISHER_NEXTIMG","Настпне зображення");
define("_MD_PUBLISHER_CLOSE","Закрити");
define("_MD_PUBLISHER_ENLARGEIMG","Збільшити");
define("_MD_PUBLISHER_OF"," з ");
