<?php
define("_MI_PUBLISHER_ADMENU1","Резюме");
define("_MI_PUBLISHER_ADMENU2","Категорії");
define("_MI_PUBLISHER_ADMENU3","Статті");
define("_MI_PUBLISHER_ADMENU4","Дозвіл");
define("_MI_PUBLISHER_ADMENU6","Тип мім");
define("_MI_PUBLISHER_ADMINHITS","Лічильник адміністратора читає?");
define("_MI_PUBLISHER_ADMINHITSDSC","Дозволити адміністратору хіти для статистики лічильника?");
define("_MI_PUBLISHER_ALLOWSUBMIT","Предсталвння користувача?");
define("_MI_PUBLISHER_ALLOWSUBMITDSC","Дозволити користувачам предсталяти статті на вашому веб-сайті?");
define("_MI_PUBLISHER_ANONPOST","Дозволити анонімне відправлення?");
define("_MI_PUBLISHER_ANONPOSTDSC","Дозволити анонімним користувачам представляти статті?");
define("_MI_PUBLISHER_AUTHOR_INFO","Розробники");
define("_MI_PUBLISHER_AUTHOR_WORD","Слова автора");
define("_MI_PUBLISHER_AUTOAPP","Автоматично схвалювати представленні статті?");
define("_MI_PUBLISHER_AUTOAPPDSC","Автоматично схвалювати представлені статті без втручання адміністратора?");
define("_MI_PUBLISHER_BCRUMB","Показати ім'я модулю в навігаційному ланцюжку?");
define("_MI_PUBLISHER_BCRUMBDSC","Якщо ві обераєте 'Так', крихта покаже \"Видавництво>назва категорії>назва статті\".<br>В іншому випадку тільки  \"назва категорії>назва статті\" буде показано.");
define("_MI_PUBLISHER_BOTH_FOOTERS","Обидві кінцеві рядки");
define("_MI_PUBLISHER_BY","по");
define("_MI_PUBLISHER_CATEGORY_ITEM_NOTIFY","Категорія предмети");
define("_MI_PUBLISHER_CATEGORY_ITEM_NOTIFY_DSC","Варіанти повідомлень, які відносяться до категорії.");
define("_MI_PUBLISHER_CATEGORY_ITEM_PUBLISHED_NOTIFY","Нова стаття опублікована");
define("_MI_PUBLISHER_CATEGORY_ITEM_PUBLISHED_NOTIFY_CAP","Сповіщати мене, коли нова стаття публікується в заданій категорії.");
define("_MI_PUBLISHER_CATEGORY_ITEM_PUBLISHED_NOTIFY_DSC","Надсилати сповіщення коли нова стаття публікується в заданій категорії.");
define("_MI_PUBLISHER_CATEGORY_ITEM_PUBLISHED_NOTIFY_SBJ","[{X_SITENAME}] {X_MODULE} автоматично повідомити: нова стаття опублікована в категорії.");
define("_MI_PUBLISHER_CATEGORY_ITEM_SUBMITTED_NOTIFY","'Представлена стаття");
define("_MI_PUBLISHER_CATEGORY_ITEM_SUBMITTED_NOTIFY_CAP","Повідомляти мене коли нова стаття представляється в категорії.");
define("_MI_PUBLISHER_CATEGORY_ITEM_SUBMITTED_NOTIFY_DSC","Оповіщення, коли нова стаття представляється в категорії.");
define("_MI_PUBLISHER_CATEGORY_ITEM_SUBMITTED_NOTIFY_SBJ","[{X_SITENAME}] {X_MODULE} автоматично повідомити: нова стаття представлена в категорії.");
define("_MI_PUBLISHER_CATLIST_IMG_W","Категорія списка ширини зображень");
define("_MI_PUBLISHER_CATLIST_IMG_WDSC","Вкажіть ширину категорії зображень при розміщенні категорії.");
define("_MI_PUBLISHER_CATMAINIMG_W","Категорія основна ширина зображення");
define("_MI_PUBLISHER_CATMAINIMG_WDSC","Вкажіть ширину категорії основного зображення.");
define("_MI_PUBLISHER_CATPERPAGE","Максимальні категорії на сторінці(сторінці користувача)?");
define("_MI_PUBLISHER_CATPERPAGEDSC","Максимальне число провідних категорій на сторінці будуть відображатися відразу в сторінці користувача?");
define("_MI_PUBLISHER_CLONE","Дозволити дублювання статті?");
define("_MI_PUBLISHER_CLONEDSC","Оберіть 'Так', щоб дозволити користувачам з відповідними дозволами дублювати статтю.");
define("_MI_PUBLISHER_COLLHEAD","Відобразити розкладний бар?");
define("_MI_PUBLISHER_COLLHEADDSC","Якщо встановити параметр 'Так', резюме категорії будуть відображатися в складному барі, а також статті. Якщо ви встановите 'Ні', складний бар не буде відображений.");
define("_MI_PUBLISHER_COMMENTS","Контролювати коментарі на рівні статті?");
define("_MI_PUBLISHER_COMMENTSDSC","якщо встановити параметр 'Так', ви побачите коментарі тільки на тих пунктах, які мають свій коментар візначений прапорцем.<br /><br />Оберіть 'Ні', щоб отримати коментарі, керовані на глобальному рівні(дивиться нижче під тегом 'Правила коментарів'.)");
define("_MI_PUBLISHER_DATEFORMAT","Формат дати:");
define("_MI_PUBLISHER_DATEFORMATDSC","Оберіть стиль відображення. Приклад: \"d-M-Y H:i\" translates to \"30-Mar-2004 22:35\"<br /><a href='http://jp.php.net/date'>Зверніться до PHP інструкції для більшої кількості варіантів відображення.</a>");
define("_MI_PUBLISHER_DEMO_SITE","SmartFactory Демо-сайт");
define("_MI_PUBLISHER_DEVELOPER_CONTRIBUTOR","Учасник(и)");
define("_MI_PUBLISHER_DEVELOPER_CREDITS","Кредити");
define("_MI_PUBLISHER_DEVELOPER_EMAIL","Електронна пошта");
define("_MI_PUBLISHER_DEVELOPER_LEAD","Провідний розробник(и)");
define("_MI_PUBLISHER_DEVELOPER_WEBSITE","Веб-сайт");
define("_MI_PUBLISHER_DISCOM","Показати підрахунок коментарів?");
define("_MI_PUBLISHER_DISCOMDSC","Оберіть 'Так' для відображення підрахнку коментарів в окремій статті.");
define("_MI_PUBLISHER_DISDATECOL","Відображати 'Опубліковано' в стовпці?");
define("_MI_PUBLISHER_DISDATECOLDSC","Коли обрано 'Підсумок', як тип відображення, оберіть 'Так', щоб відобразити 'Опубліковано' дати в таблиці елементів на сторінці індексу і категорії.");
define("_MI_PUBLISHER_DCS","Відображати зведення категорії?");
define("_MI_PUBLISHER_DCS_DSC","Оберіть 'Ні', щоб не відображати зведення категорії на сторінку категорії, яка не має підкатегорій.");
define("_MI_PUBLISHER_DISPLAYTYPE_FULL","Повний перегляд");
define("_MI_PUBLISHER_DISPLAYTYPE_LIST","Маркований список");
define("_MI_PUBLISHER_DISPLAYTYPE_WFSECTION","WF стиль Розділу");
define("_MI_PUBLISHER_DISPLAYTYPE_SUMMARY","Сумарний перегляд");
define("_MI_PUBLISHER_DISSBCATDSC","Відображати опис підкатегорій?");
define("_MI_PUBLISHER_DISSBCATDSCDSC","Оберіть 'Так', щоб відобразити опис підкатегорій в індексі та сторінці категорії.");
define("_MI_PUBLISHER_DISTYPE","Тип відображення статей:");
define("_MI_PUBLISHER_DISTYPEDSC","якщо 'Сумарний перегляд' обраний, тільки назва, дата і хіти кожного елемента буде відображатися в обраній категорії. Якщо 'Повний перегляд' обраний, кожна стаття буде повністю відображатись в обраній категорії.");
define("_MI_PUBLISHER_FOOTERPRINT","Роздрукувати сторінку нижнього колонтитула");
define("_MI_PUBLISHER_FOOTERPRINTDSC","Нижній колонтитул буде доздрукований для кожної статті");
define("_MI_PUBLISHER_GLOBAL_ITEM_CATEGORY_CREATED_NOTIFY","Нова категорія");
define("_MI_PUBLISHER_GLOBAL_ITEM_CATEGORY_CREATED_NOTIFY_CAP","Повідомити мене, коли нова категорія буде створена.");
define("_MI_PUBLISHER_GLOBAL_ITEM_CATEGORY_CREATED_NOTIFY_DSC","Надіслати повідомлення, коли нова стаття буде створена.");
define("_MI_PUBLISHER_GLOBAL_ITEM_CATEGORY_CREATED_NOTIFY_SBJ","[{X_SITENAME}] {X_MODULE} автоматичне повідомлення: Нова категорія");
define("_MI_PUBLISHER_GLOBAL_ITEM_NOTIFY","Глобальні статті");
define("_MI_PUBLISHER_GLOBAL_ITEM_NOTIFY_DSC","Варіанти повідомлень, які застосовуються до всіх статей.");
define("_MI_PUBLISHER_GLOBAL_ITEM_PUBLISHED_NOTIFY","Нова стаття опублікована");
define("_MI_PUBLISHER_GLOBAL_ITEM_PUBLISHED_NOTIFY_CAP","Повідомити мене, коли нова категорія буде опублікована.");
define("_MI_PUBLISHER_GLOBAL_ITEM_PUBLISHED_NOTIFY_DSC","Надіслати повідомлення, коли нова стаття буде опублікована.");
define("_MI_PUBLISHER_GLOBAL_ITEM_PUBLISHED_NOTIFY_SBJ","[{X_SITENAME}] {X_MODULE} автоматичне повідомлення: Нова стаття опублікована");
define("_MI_PUBLISHER_GLOBAL_ITEM_SUBMITTED_NOTIFY","Представлена стаття");
define("_MI_PUBLISHER_GLOBAL_ITEM_SUBMITTED_NOTIFY_CAP","Повідомити мене, коли стаття буде представлена й очікує затвердження.");
define("_MI_PUBLISHER_GLOBAL_ITEM_SUBMITTED_NOTIFY_DSC","Надіслати повідомлення, коли стаття буде представлена й очікує затвердження.");
define("_MI_PUBLISHER_GLOBAL_ITEM_SUBMITTED_NOTIFY_SBJ","[{X_SITENAME}] {X_MODULE} автоматичне повідомлення: Нова стаття представлена");
define("_MI_PUBLISHER_HEADERPRINT","Роздрукувати сторінку верхнього колонтитула");
define("_MI_PUBLISHER_HEADERPRINTDSC","Верхній колонтитул, що буде роздрукований для кожної статті");
define("_MI_PUBLISHER_HITSCOL","Відображати 'Хіти' стовпець?");
define("_MI_PUBLISHER_HITSCOLDSC","При виборі 'Зведення' тип відображення, оберіть 'Так', щоб відобразити стовпець 'Хіти' в таблиці елементів на сторінці індексу і категорії.");
define("_MI_PUBLISHER_HLCOLOR","Виделіть колір для ключових слів.");
define("_MI_PUBLISHER_HLCOLORDSC","Колів підсвічування ключових слів для функції пошуку.");
define("_MI_PUBLISHER_IMAGENAV","Використовуйте зображення навігації сторінки:");
define("_MI_PUBLISHER_IMAGENAVDSC","якщо ви оберете опцію 'Так', сторінка навігації буде відображатися з зображеннями, в іншому випадку, буде використовуватися оригінальна сторінка навігації.");
define("_MI_PUBLISHER_INDEXFOOTER","Індекс нижнього колонтитулу");
define("_MI_PUBLISHER_INDEXFOOTER_SEL","Індекс нижнього колонтитулу");
define("_MI_PUBLISHER_INDEXFOOTERDSC","Нижній колонтитул буде відображений в сторінці індексу модуля.");
define("_MI_PUBLISHER_INDEXMSG","Головна сторінка вітальне повідомлення:");
define("_MI_PUBLISHER_INDEXMSGDEF","");
define("_MI_PUBLISHER_INDEXMSGDSC","Вітальне повідомлення буде відображатися на головній сторінці модуля.");
define("_MI_PUBLISHER_ITEM_APPROVED_NOTIFY","Стаття затверджена");
define("_MI_PUBLISHER_ITEM_APPROVED_NOTIFY_CAP","Повідомити мене, коли стаття буде затверджена.");
define("_MI_PUBLISHER_ITEM_APPROVED_NOTIFY_DSC","Надіслати повідомлення , коли стаття буде затверджена.");
define("_MI_PUBLISHER_ITEM_APPROVED_NOTIFY_SBJ","[{X_SITENAME}] {X_MODULE} автоматичне повідомлення: стаття затверджена.");
define("_MI_PUBLISHER_ITEM_NOTIFY","Стаття");
define("_MI_PUBLISHER_ITEM_NOTIFY_DSC","Варіанти повідомлень, які відносяться до даної статті.");
define("_MI_PUBLISHER_ITEM_REJECTED_NOTIFY","Стаття відхилена");
define("_MI_PUBLISHER_ITEM_REJECTED_NOTIFY_CAP","Повідомили мене, якщо ця стаття буде відхилена.");
define("_MI_PUBLISHER_ITEM_REJECTED_NOTIFY_DSC","Отримати повідомлення, якщо стаття буде відхилена.");
define("_MI_PUBLISHER_ITEM_REJECTED_NOTIFY_SBJ","[{X_SITENAME}] {X_MODULE} автоматичне повідомлення: стаття відхилена");
define("_MI_PUBLISHER_ITEMFOOTER","Пункт нижній колонтитул");
define("_MI_PUBLISHER_ITEMFOOTER_SEL","Пункт нижній колонтитул");
define("_MI_PUBLISHER_ITEMFOOTERDSC","Нижній колонтитул буде відображений в кожній статті.");
define("_MI_PUBLISHER_ITEMSMENU","Блок категорії меню");
//bd tree block hack
define("_MI_PUBLISHER_ITEMSTREE","Блок_дерево");
//--/bd
define("_MI_PUBLISHER_ITEMSNEW","Список останні елементи");
define("_MI_PUBLISHER_ITEMSPOT","У центрі уваги!");
define("_MI_PUBLISHER_ITEMSRANDOM_ITEM","Випадковий елемент!");
define("_MI_PUBLISHER_LASTITEM","Відображати останній стовпчик елементу?");
define("_MI_PUBLISHER_LASTITEMDSC","Оберіть 'Так', для відображення останнього елементу в кожній категорії на головній сторінці та категорії.");
define("_MI_PUBLISHER_LASTITEMS","Відображати список недавно опублікований статей?");
define("_MI_PUBLISHER_LASTITEMSDSC","Оберіть 'Так', щоб отримати список в нижній частині сторінки модуля.");
define("_MI_PUBLISHER_LASTITSIZE","Останній елемент розміру:");
define("_MI_PUBLISHER_LASTITSIZEDSC","Виберіть максимальній розмір назви в останньому елементі стовпця.");
define("_MI_PUBLISHER_LINKPATH","Включити посилання на поточному шляху:");
define("_MI_PUBLISHER_LINKPATHDSC","Ця функція дозволяє користувачеві зворотній шлях, натиснувши на елемент доріжки, що відображається в верхній частині сторінки.");
define("_MI_PUBLISHER_MAX_HEIGHT","Завантаження максимальної висоти зображення");
define("_MI_PUBLISHER_MAX_HEIGHTDSC","Максимальна висота графічного файлу, який ви можете завантажити.");
define("_MI_PUBLISHER_MAX_SIZE","Максимальний розмір файлу");
define("_MI_PUBLISHER_MAX_SIZEDSC","Максимальний розмір (в байтах) файлу, який може бути завантажений.");
define("_MI_PUBLISHER_MAX_WIDTH","Максимальна ширина завантаженного зображення");
define("_MI_PUBLISHER_MAX_WIDTHDSC","Максимальна ширина зображення файлу, який може бути завантажений.");
define("_MI_PUBLISHER_MD_DESC","Публікації рішення для вашого XOOPS сайту ");
define("_MI_PUBLISHER_MD_NAME","Видавець");
define("_MI_PUBLISHER_MODULE_BUG","Повідомити про помилку цього модуля");
define("_MI_PUBLISHER_MODULE_DEMO","Демоверсія сайту");
define("_MI_PUBLISHER_MODULE_DISCLAIMER","Відмова");
define("_MI_PUBLISHER_MODULE_FEATURE","Запропонувати нову функцію для цього модуля");
define("_MI_PUBLISHER_MODULE_INFO","Деталі розробки модулів");
define("_MI_PUBLISHER_MODULE_RELEASE_DATE","Дата випуску");
define("_MI_PUBLISHER_MODULE_STATUS","Статус");
define("_MI_PUBLISHER_MODULE_SUBMIT_BUG","Представити помилку");
define("_MI_PUBLISHER_MODULE_SUBMIT_FEATURE","Відправити запит на виділення");
define("_MI_PUBLISHER_MODULE_SUPPORT","Офіційний сайт підтримки");
define("_MI_PUBLISHER_NO_FOOTERS","Жоден");
define("_MI_PUBLISHER_ORDERBY","Порядок сортування");
define("_MI_PUBLISHER_ORDERBY_DATE","DESC Дата");
define("_MI_PUBLISHER_ORDERBY_TITLE","ASC Назва");
define("_MI_PUBLISHER_ORDERBY_WEIGHT","ASC Вага");
define("_MI_PUBLISHER_ORDERBYDSC","Виберіть порядок сортування елементів по всьому модулю.");
define("_MI_PUBLISHER_OTHER_ITEMS_TYPE_ALL","Всі статті");
define("_MI_PUBLISHER_OTHER_ITEMS_TYPE_NONE","Жодна");
define("_MI_PUBLISHER_OTHER_ITEMS_TYPE_PREVIOUS_NEXT","Попередня та наступна стаття");
define("_MI_PUBLISHER_OTHERITEMS","Інші стаття відображаються");
define("_MI_PUBLISHER_OTHERITEMSDSC","Виберіть, як ви хотіли б, відобразити інші статті категорії на сторінці статті.");
define("_MI_PUBLISHER_PERPAGE","Максимальна кількість статей на сторінку (сторінка адміністрітора):");
define("_MI_PUBLISHER_PERPAGEDSC","Максимальна кількість статей на сторінці будуть відображатися відразу в стороні адміністратора.");
define("_MI_PUBLISHER_PERPAGEINDEX","Максимальна кількість статей на сторінку (сторінка користувача):");
define("_MI_PUBLISHER_PERPAGEINDEXDSC","Максимальна кількість статей на сторінку,  що будуть відображатись разом на стороні користувача.");
define("_MI_PUBLISHER_PRINTLOGOURL","URL логотип для друку");
define("_MI_PUBLISHER_PRINTLOGOURLDSC","URL логотип, який буде надрукований на верхній сторінці.");
define("_MI_PUBLISHER_RECENTITEMS","Останні пункти (докладно)");
define("_MI_PUBLISHER_SHOW_RSS","Показати посилання на RSS-канал");
define("_MI_PUBLISHER_SHOW_RSSDSC","");
define("_MI_PUBLISHER_SHOW_SUBCATS","Відображати підкатегорії");
define("_MI_PUBLISHER_SHOW_SUBCATS_ALL","Відображати всі підкатегорії");
define("_MI_PUBLISHER_SHOW_SUBCATS_DSC","Оберіть, якщо ви хочете, щоб відображались підкатегорії в списку категорій на головній на сторінці категорій модуля.");
define("_MI_PUBLISHER_SHOW_SUBCATS_NO","Не відображати підкатегорії");
define("_MI_PUBLISHER_SHOW_SUBCATS_NOMAIN","Не відображати підкатегорії на головній сторінці, а на сторінці категорій");
define("_MI_PUBLISHER_SHOW_SUBCATS_NOTEMPTY","Не відображати порожні підкатегорії");
define("_MI_PUBLISHER_SUB_SMNAME1","Представити статтю");
define("_MI_PUBLISHER_SUBMITMSG","Представити сторінку з вступним повідомленням:");
define("_MI_PUBLISHER_SUBMITMSGDEF","");
define("_MI_PUBLISHER_SUBMITMSGDSC","Вступне повідомлення буде відображатись на представленій сторінці модуля.");
define("_MI_PUBLISHER_TITLE_SIZE","Розмір назви:");
define("_MI_PUBLISHER_TITLE_SIZEDSC","Налаштувати максимальний розмір назви на сторінці одного елемента.");
define("_MI_PUBLISHER_UPLOAD","Завантажити файл користувача?");
define("_MI_PUBLISHER_UPLOADDSC","Дозволити користувачам завантажувати файли з посиланнями на статті на вашому веб-сайті?");
define("_MI_PUBLISHER_USEREALNAME","Використовуйте дійсне ім'я користувачів");
define("_MI_PUBLISHER_USEREALNAMEDSC","При відображенні імені користувача, використовуйте реальне ім'я цього користувача, якщо воно вказано.");
define("_MI_PUBLISHER_VERSION_HISTORY","Історія версій");
define("_MI_PUBLISHER_WELCOME","Відображення вітального заголовку та повідомлення:");
define("_MI_PUBLISHER_WELCOMEDSC","якщо стоїть парамет 'Так', модуль головної сторінки буде відображатись із заголовком 'Ласкаво просимо в Pubisher…', а потім вітальне повідомлення визначене нижче. Якщо стоїть параметр 'Ні', жодна з цих ліній не буде відображатись.");
define("_MI_PUBLISHER_WHOWHEN","Відображати плакат і дату?");
define("_MI_PUBLISHER_WHOWHENDSC","Оберіть 'Так', щоб відобразити плакат і дату в окремій статті.");
define("_MI_PUBLISHER_PV_TEXT","Частковий перегляд повідомлення");
define("_MI_PUBLISHER_PV_TEXTDSC","Повідомлення для статей, що допускають тільки частковий вид.");
define("_MI_PUBLISHER_PV_TEXT_DEF","Щоб переглянути повну статтю, ви повинні зареєструватися.");
define("_MI_PUBLISHER_SEOMODNAME","URL Переписуюче ім'я модулю");
define("_MI_PUBLISHER_SEOMODNAMEDSC","Якщо URL перезапис включен для модуля, це ім'я модуля, яке буде використовуватися. Наприклад: http://yoursite.com/publisher/...");
define("_MI_PUBLISHER_ARTCOUNT","Показати підсумок статей");
define("_MI_PUBLISHER_ARTCOUNTDSC","Оберіть 'Так', щоб відобразити лічильник статті в межах кожної категорії в категорії зведеної таблиці. Зверніть увагу, що модуль в даний час тільки підраховує статті в кожній категорії і не враховується в підкатегорії.");
define("_MI_PUBLISHER_LATESTFILES","Останні завантаженні файли");
define("_MI_PUBLISHER_PATHSEARCH","Відображати шлях пошуку категорії");
define("_MI_PUBLISHER_PATHSEARCHDSC","");
define("_MI_PUBLISHER_DISPBREAD","Показати панель навігації");
define("_MI_PUBLISHER_DISPBREADDSC","Панель навігації відображає контекст поточної сторінки в структурі сайту.");
define("_MI_PUBLISHER_DATE_TO_DATE","Статті від дати до дати");
//added in publisher
define("_MI_PUBLISHER_FORM_STATUS","Оберіть статус за замовчуванням для представленної статті.");
define("_MI_PUBLISHER_FORM_STATUS_DSC","");
define("_MI_PUBLISHER_PUBLISHED","Опубліковано");
define("_MI_PUBLISHER_OFFLINE","Не в мережі");
define("_MI_PUBLISHER_SUBMITTED","Представлено");
define("_MI_PUBLISHER_REJECTED","Відхилено");
define("_MI_PUBLISHER_FORM_ALLOWCOMMENTS","“Дозволити коментарі” вставлено в значення TRUE");
define("_MI_PUBLISHER_FORM_ALLOWCOMMENTS_DSC","");
define("_MI_PUBLISHER_FORM_DOHTML","“Включити HTML теги” встановлено в значення TRUE");
define("_MI_PUBLISHER_FORM_DOHTML_DSC","");
define("_MI_PUBLISHER_FORM_DOSMILEY","“Enable smiley icons” set to TRUE");
define("_MI_PUBLISHER_FORM_DOSMILEY_DSC","");
define("_MI_PUBLISHER_FORM_DOXCODE","“Включити іконки смайликів” вставлено в значення TRUE");
define("_MI_PUBLISHER_FORM_DOXCODE_DSC","");
define("_MI_PUBLISHER_FORM_DOIMAGE","“Включити зображення” вставлено в значення TRUE");
define("_MI_PUBLISHER_FORM_DOIMAGE_DSC","");
define("_MI_PUBLISHER_FORM_DOBR","“Включити розрив рядка” вставлено в значення TRUE");
define("_MI_PUBLISHER_FORM_DOBR_DSC","");
define("_MI_PUBLISHER_EDITOR","Тип редактора за замовчуванням");
define("_MI_PUBLISHER_EDITOR_DSC","Який редактор ви би хотіли використовувати за замовчуванням? Ви також можете відправникам вибрати редактори в меню дозволів.");
define("_MI_PUBLISHER_EDITOR_ROWS","Редактор кількості рядків");
define("_MI_PUBLISHER_EDITOR_ROWS_DSC","");
define("_MI_PUBLISHER_EDITOR_COLS","Редактор кількості стовпців");
define("_MI_PUBLISHER_EDITOR_COLS_DSC","");
define("_MI_PUBLISHER_EDITOR_WIDTH","Редактор ширини");
define("_MI_PUBLISHER_EDITOR_WIDTH_DSC","");
define("_MI_PUBLISHER_EDITOR_HEIGHT","Редактор висоти");
define("_MI_PUBLISHER_EDITOR_HEIGHT_DSC","");
//blocks descriptions
define("_MI_PUBLISHER_ITEMSNEW_DSC","Показати нові елементи");
define("_MI_PUBLISHER_RECENTITEMS_DSC","Показати недавні елементи");
define("_MI_PUBLISHER_ITEMSPOT_DSC","Показати останні елементи");
define("_MI_PUBLISHER_ITEMSRANDOM_ITEM_DSC","Показати випадковий 'елемент' елемент");
define("_MI_PUBLISHER_ITEMSMENU_DSC","Меню відображення категорій");
define("_MI_PUBLISHER_LATESTFILES_DSC","Список останніх завантантаженних файлів");
define("_MI_PUBLISHER_DATE_TO_DATE_DSC","Список статей від обраної дати до іншої");
define("_MI_PUBLISHER_ITEMSTREE_DSC","Відображати скатегорію та елементи дерева");
//templates descriptions
define("_MI_PUBLISHER_HEADER_DSC","Відображати верхній колонтитул");
define("_MI_PUBLISHER_FOOTER_DSC","Відображати нижній колонтитул");
define("_MI_PUBLISHER_SINGLEITEM_DSC","Відображати один елемент");
define("_MI_PUBLISHER_CATEGORIES_TABLE_DSC","Відображати список таблиць, що використовуються в інших шаблонах");
define("_MI_PUBLISHER_DISPLAY_LIST_DSC","Відображати індекс і категорію в типом відображення куля");
define("_MI_PUBLISHER_DISPLAY_SUMMARY_DSC","Відображати індекс і категорію з коротким типом відображення");
define("_MI_PUBLISHER_DISPLAY_FULL_DSC","Відображати індекс і категорію з повним типом відображення");
define("_MI_PUBLISHER_DISPLAY_WFSECTION_DSC","Відображати індекс і категорію в WF-секції, як стиль");
define("_MI_PUBLISHER_ITEM_DSC","Відображати елемент");
define("_MI_PUBLISHER_ARCHIVE__DSC","Архіви статей");
define("_MI_PUBLISHER_SUBMIT_DSC","Форма для представлення елементу");
define("_MI_PUBLISHER_SINGLEITEM_BLOCK_DSC","Відображати один елемент в блоці");
define("_MI_PUBLISHER_PRINT_DSC","Роздрукувати шаблон сторінки");
define("_MI_PUBLISHER_RSS_DSC","Відображати видавець RSS-подача");
define("_MI_PUBLISHER_ADDFILE_DSC","Форма для додавання файлу до статті");
define("_MI_PUBLISHER_WARNING_ALPHA","Цей модуль поставляється як є, без будь-яких гарантій взагалі. Цей модуль ALPHA, означає, що він все ще знаходиться під активним розвитком. Цей випуск призначений для <strong>з метою тестування тільки</strong>і ми<strong>сильно</strong> рекомендуємо вам не використовувати його на живому сайті або у виборочному середовищі.");
define("_MI_PUBLISHER_PEOPLE_DEVELOPERS","Розробники");
define("_MI_PUBLISHER_PEOPLE_TESTERS","Тестеровщики");
define("_MI_PUBLISHER_PEOPLE_DOCUMENTERS","Укладачі документації");
define("_MI_PUBLISHER_PEOPLE_TRANSLATERS","Перекладачі");
define("_MI_PUBLISHER_PEOPLE_OTHER","Інші учасники");
define("_MI_PUBLISHER_URL_REWRITE","URL метод перепису");
define("_MI_PUBLISHER_URL_REWRITE_DSC","Якщо ви вибираєте htaccess, то не забудьте покласти файл “.htaccess” в кореневу папку");
define("_MI_PUBLISHER_URL_REWRITE_NONE","Жоден");
define("_MI_PUBLISHER_URL_REWRITE_PATHINFO","Шлях-інфо");
define("_MI_PUBLISHER_URL_REWRITE_HTACCESS","Htaccess");
define("_MI_PUBLISHER_CONFCAT_SEO","SEO");
define("_MI_PUBLISHER_CONFCAT_SEO_DSC","Налаштування для перезапису методу, метадані і т.д.");
define("_MI_PUBLISHER_CONFCAT_FORMAT","Формат");
define("_MI_PUBLISHER_CONFCAT_FORMAT_DSC","");
define("_MI_PUBLISHER_CONFCAT_PRINT","Роздрукувати сторінку");
define("_MI_PUBLISHER_CONFCAT_PRINT_DSC","");
define("_MI_PUBLISHER_CONFCAT_OTHERS","Інше");
define("_MI_PUBLISHER_CONFCAT_OTHERS_DSC","");
define("_MI_PUBLISHER_CONFCAT_PERMISSIONS","Дозволи");
define("_MI_PUBLISHER_CONFCAT_PERMISSIONS_DSC","");
define("_MI_PUBLISHER_COLUMNS","Стовпці");
define("_MI_PUBLISHER_COLUMNS_DSC","");
define("_MI_PUBLISHER_ALLOWRATING","Дозволити рейтинг функцію");
define("_MI_PUBLISHER_ALLOWRATING_DSC","Ви можете обрати, хто може оціінювати в рейтинг функції");
define("_MI_PUBLISHER_ALLOWSEARCH","Дозволити розширену функцію пошуку");
define("_MI_PUBLISHER_ALLOWSEARCH_DSC","Ви можете обрати, хто може шукати в закладці дозволів");
define("_MI_PUBLISHER_SUB_SMNAME3","Пошук");
define("_MI_PUBLISHER_LATEST_NEWS","Останні новини");
define("_MI_PUBLISHER_LATEST_NEWS_DSC","");
define("_MI_PUBLISHER_SEARCH","Блок пошуку");
define("_MI_PUBLISHER_SEARCH_DSC","Сторінка розширеного пошуку");
define("_MI_PUBLISHER_CATEGORY_ITEMS_SEL","Категорія пункти вибору");
define("_MI_PUBLISHER_CATEGORY_ITEMS_SEL_DSC","Показує, що випадає поле вибору з елементами, згруповані за категоріями");
define("_MI_PUBLISHER_CONFCAT_INDEX","Головна сторінка");
define("_MI_PUBLISHER_CONFCAT_INDEX_DSC","");
define("_MI_PUBLISHER_CONFCAT_CATEGORY","Сторінка категорії");
define("_MI_PUBLISHER_CONFCAT_CATEGORY_DSC","");
define("_MI_PUBLISHER_CONFCAT_ITEM","Сторінка товару");
define("_MI_PUBLISHER_CONFCAT_ITEM_DSC","");
define("_MI_PUBLISHER_CONFCAT_SUBMIT","Додати сторінку");
define("_MI_PUBLISHER_CONFCAT_SUBMIT_DSC","Додати макет сторінки і сформувати значення за замовчуванням");
define("_MI_PUBLISHER_CONFCAT_INDEXCAT","Головна та сторінка категорії");
define("_MI_PUBLISHER_CONFCAT_INDEXCAT_DSC","");
define("_MI_PUBLISHER_CONFCAT_SEARCH","Пошукова сторінка");
define("_MI_PUBLISHER_CONFCAT_SEARCH_DSC","");
define("_MI_PUBLISHER_SEO_METAKEYWORDS","Мета ключові слова");
define("_MI_PUBLISHER_SEO_METAKEYWORDS_DSC","Ці ключові слова будуть об'єднані з ключовими словами, встановленими статтями. Використовуйте "," для їх поділу.");
define("_MI_PUBLISHER_SUB_ARCHIVE","Архів");
define("_MI_PUBLISHER_ALLOW_AUTHOR_ITEMS","Дозволити елементи особливості автора");
define("_MI_PUBLISHER_ALLOW_AUTHOR_ITEMS_DSC","");
define("_MI_PUBLISHER_AUTHOR_ITEMS_DSC","Показати товари того ж автора");
define("_MI_PUBLISHER_DISP_BLOCK_SUM","Відображати короткий зміст блоків на сторінці елементів?");
define("_MI_PUBLISHER_DISP_BLOCK_SUM_DSC","");
define("_MI_PUBLISHER_ADMENU0","Додому");
define("_MI_PUBLISHER_DISP_INDEX_SUB","Відображати субтитри на головній сторінці?");
define("_MI_PUBLISHER_DISP_INDEX_SUB_DSC","");
define("_MI_PUBLISHER_DISP_CAT_SUB","Відображати субтитри на сторінці категорії?");
define("_MI_PUBLISHER_DISP_CAT_SUB_DSC","");
define("_MI_PUBLISHER_DISP_ITEM_SUB","Відображати субтитри на сторінці товару?");
define("_MI_PUBLISHER_DISP_ITEM_SUB_DSC","");
//30/04/2012
define("_MI_PUBLISHER_ALLOWEDIT","Редагувати статтю користувача?");
define("_MI_PUBLISHER_ALLOWEDITDSC","Дозволити користувачам редагувати їх власні статті?");
define("_MI_PUBLISHER_ALLOWDELETE","Видалити статтю користувача?");
define("_MI_PUBLISHER_ALLOWDELETEDSC","Дозволити користувачам видаляти їх власні статті?");

//1.02 Beta 2
define("_MI_PUBLISHER_DISPLAY_PDF","Відображати іконку PDF");
define("_MI_PUBLISHER_DISPLAY_PDF_DSC","Оберіть Так, щоб показати PDF іконку та дозволити користувачам створювати PDF файли");
